//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndignadoWeb.SessionServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTLoginInfo", Namespace="http://schemas.datacontract.org/2004/07/IndignadoServer.Services")]
    [System.SerializableAttribute()]
    public partial class DTLoginInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isMovAdminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isSysAdminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isMovAdmin {
            get {
                return this.isMovAdminField;
            }
            set {
                if ((this.isMovAdminField.Equals(value) != true)) {
                    this.isMovAdminField = value;
                    this.RaisePropertyChanged("isMovAdmin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isSysAdmin {
            get {
                return this.isSysAdminField;
            }
            set {
                if ((this.isSysAdminField.Equals(value) != true)) {
                    this.isSysAdminField = value;
                    this.RaisePropertyChanged("isSysAdmin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                if ((object.ReferenceEquals(this.tokenField, value) != true)) {
                    this.tokenField = value;
                    this.RaisePropertyChanged("token");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginFault", Namespace="http://schemas.datacontract.org/2004/07/IndignadoServer.Services")]
    [System.SerializableAttribute()]
    public partial class LoginFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IssueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IndignadoWeb.SessionServiceReference.DTLoginFaultType TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Issue {
            get {
                return this.IssueField;
            }
            set {
                if ((object.ReferenceEquals(this.IssueField, value) != true)) {
                    this.IssueField = value;
                    this.RaisePropertyChanged("Issue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IndignadoWeb.SessionServiceReference.DTLoginFaultType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTLoginFaultType", Namespace="http://schemas.datacontract.org/2004/07/IndignadoServer.Services")]
    public enum DTLoginFaultType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UNKOWN_OR_INVALID = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FB_NOT_REGISTERED = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTRegisterModel", Namespace="http://schemas.datacontract.org/2004/07/IndignadoServer.Services")]
    [System.SerializableAttribute()]
    public partial class DTRegisterModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apodoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string contraseñaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idMovimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float latitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float longitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apodo {
            get {
                return this.apodoField;
            }
            set {
                if ((object.ReferenceEquals(this.apodoField, value) != true)) {
                    this.apodoField = value;
                    this.RaisePropertyChanged("apodo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string contraseña {
            get {
                return this.contraseñaField;
            }
            set {
                if ((object.ReferenceEquals(this.contraseñaField, value) != true)) {
                    this.contraseñaField = value;
                    this.RaisePropertyChanged("contraseña");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idMovimiento {
            get {
                return this.idMovimientoField;
            }
            set {
                if ((this.idMovimientoField.Equals(value) != true)) {
                    this.idMovimientoField = value;
                    this.RaisePropertyChanged("idMovimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float latitud {
            get {
                return this.latitudField;
            }
            set {
                if ((this.latitudField.Equals(value) != true)) {
                    this.latitudField = value;
                    this.RaisePropertyChanged("latitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float longitud {
            get {
                return this.longitudField;
            }
            set {
                if ((this.longitudField.Equals(value) != true)) {
                    this.longitudField = value;
                    this.RaisePropertyChanged("longitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mail {
            get {
                return this.mailField;
            }
            set {
                if ((object.ReferenceEquals(this.mailField, value) != true)) {
                    this.mailField = value;
                    this.RaisePropertyChanged("mail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTUserCreateStatus", Namespace="http://schemas.datacontract.org/2004/07/IndignadoServer.Services")]
    public enum DTUserCreateStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidUserName = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidPassword = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidEmail = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DuplicateUserName = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DuplicateEmail = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GenericError = 8,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTRegisterFBModel", Namespace="http://schemas.datacontract.org/2004/07/IndignadoServer.Services")]
    [System.SerializableAttribute()]
    public partial class DTRegisterFBModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idMovimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float latitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float longitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idMovimiento {
            get {
                return this.idMovimientoField;
            }
            set {
                if ((this.idMovimientoField.Equals(value) != true)) {
                    this.idMovimientoField = value;
                    this.RaisePropertyChanged("idMovimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float latitud {
            get {
                return this.latitudField;
            }
            set {
                if ((this.latitudField.Equals(value) != true)) {
                    this.latitudField = value;
                    this.RaisePropertyChanged("latitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float longitud {
            get {
                return this.longitudField;
            }
            set {
                if ((this.longitudField.Equals(value) != true)) {
                    this.longitudField = value;
                    this.RaisePropertyChanged("longitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                if ((object.ReferenceEquals(this.tokenField, value) != true)) {
                    this.tokenField = value;
                    this.RaisePropertyChanged("token");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTTenantInfo", Namespace="http://schemas.datacontract.org/2004/07/IndignadoServer.Services")]
    [System.SerializableAttribute()]
    public partial class DTTenantInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool habilitadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string layoutFileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string logoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool habilitado {
            get {
                return this.habilitadoField;
            }
            set {
                if ((this.habilitadoField.Equals(value) != true)) {
                    this.habilitadoField = value;
                    this.RaisePropertyChanged("habilitado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string layoutFile {
            get {
                return this.layoutFileField;
            }
            set {
                if ((object.ReferenceEquals(this.layoutFileField, value) != true)) {
                    this.layoutFileField = value;
                    this.RaisePropertyChanged("layoutFile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string logo {
            get {
                return this.logoField;
            }
            set {
                if ((object.ReferenceEquals(this.logoField, value) != true)) {
                    this.logoField = value;
                    this.RaisePropertyChanged("logo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SessionServiceReference.ISessionService")]
    public interface ISessionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionService/Login", ReplyAction="http://tempuri.org/ISessionService/LoginResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(IndignadoWeb.SessionServiceReference.LoginFault), Action="http://tempuri.org/ISessionService/LoginLoginFaultFault", Name="LoginFault", Namespace="http://schemas.datacontract.org/2004/07/IndignadoServer.Services")]
        IndignadoWeb.SessionServiceReference.DTLoginInfo Login(int idMovmiento, string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionService/LoginFB", ReplyAction="http://tempuri.org/ISessionService/LoginFBResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(IndignadoWeb.SessionServiceReference.LoginFault), Action="http://tempuri.org/ISessionService/LoginFBLoginFaultFault", Name="LoginFault", Namespace="http://schemas.datacontract.org/2004/07/IndignadoServer.Services")]
        IndignadoWeb.SessionServiceReference.DTLoginInfo LoginFB(int idMovimiento, string accesToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionService/RegisterUser", ReplyAction="http://tempuri.org/ISessionService/RegisterUserResponse")]
        IndignadoWeb.SessionServiceReference.DTUserCreateStatus RegisterUser(IndignadoWeb.SessionServiceReference.DTRegisterModel user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionService/RegisterFBUser", ReplyAction="http://tempuri.org/ISessionService/RegisterFBUserResponse")]
        IndignadoWeb.SessionServiceReference.DTUserCreateStatus RegisterFBUser(IndignadoWeb.SessionServiceReference.DTRegisterFBModel user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionService/ValidateToken", ReplyAction="http://tempuri.org/ISessionService/ValidateTokenResponse")]
        bool ValidateToken(int idMovmiento, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionService/GetTenantInfo", ReplyAction="http://tempuri.org/ISessionService/GetTenantInfoResponse")]
        IndignadoWeb.SessionServiceReference.DTTenantInfo GetTenantInfo(string movimiento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionService/ValidateRegUser", ReplyAction="http://tempuri.org/ISessionService/ValidateRegUserResponse")]
        bool ValidateRegUser();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionService/ValidateMovAdmin", ReplyAction="http://tempuri.org/ISessionService/ValidateMovAdminResponse")]
        bool ValidateMovAdmin();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionService/ValidateSysAdmin", ReplyAction="http://tempuri.org/ISessionService/ValidateSysAdminResponse")]
        bool ValidateSysAdmin();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISessionServiceChannel : IndignadoWeb.SessionServiceReference.ISessionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SessionServiceClient : System.ServiceModel.ClientBase<IndignadoWeb.SessionServiceReference.ISessionService>, IndignadoWeb.SessionServiceReference.ISessionService {
        
        public SessionServiceClient() {
        }
        
        public SessionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SessionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SessionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SessionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public IndignadoWeb.SessionServiceReference.DTLoginInfo Login(int idMovmiento, string userName, string password) {
            return base.Channel.Login(idMovmiento, userName, password);
        }
        
        public IndignadoWeb.SessionServiceReference.DTLoginInfo LoginFB(int idMovimiento, string accesToken) {
            return base.Channel.LoginFB(idMovimiento, accesToken);
        }
        
        public IndignadoWeb.SessionServiceReference.DTUserCreateStatus RegisterUser(IndignadoWeb.SessionServiceReference.DTRegisterModel user) {
            return base.Channel.RegisterUser(user);
        }
        
        public IndignadoWeb.SessionServiceReference.DTUserCreateStatus RegisterFBUser(IndignadoWeb.SessionServiceReference.DTRegisterFBModel user) {
            return base.Channel.RegisterFBUser(user);
        }
        
        public bool ValidateToken(int idMovmiento, string token) {
            return base.Channel.ValidateToken(idMovmiento, token);
        }
        
        public IndignadoWeb.SessionServiceReference.DTTenantInfo GetTenantInfo(string movimiento) {
            return base.Channel.GetTenantInfo(movimiento);
        }
        
        public bool ValidateRegUser() {
            return base.Channel.ValidateRegUser();
        }
        
        public bool ValidateMovAdmin() {
            return base.Channel.ValidateMovAdmin();
        }
        
        public bool ValidateSysAdmin() {
            return base.Channel.ValidateSysAdmin();
        }
    }
}
