//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.530
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndignadoWeb.TestServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TestServiceReference.ITestService")]
    public interface ITestService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestService/PingPublic", ReplyAction="http://tempuri.org/ITestService/PingPublicResponse")]
        string PingPublic(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestService/PingUsers", ReplyAction="http://tempuri.org/ITestService/PingUsersResponse")]
        string PingUsers(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestService/PingMovAdmin", ReplyAction="http://tempuri.org/ITestService/PingMovAdminResponse")]
        string PingMovAdmin(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestService/PingSysAdmin", ReplyAction="http://tempuri.org/ITestService/PingSysAdminResponse")]
        string PingSysAdmin(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITestServiceChannel : IndignadoWeb.TestServiceReference.ITestService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TestServiceClient : System.ServiceModel.ClientBase<IndignadoWeb.TestServiceReference.ITestService>, IndignadoWeb.TestServiceReference.ITestService {
        
        public TestServiceClient() {
        }
        
        public TestServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TestServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TestServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TestServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string PingPublic(string name) {
            return base.Channel.PingPublic(name);
        }
        
        public string PingUsers(string name) {
            return base.Channel.PingUsers(name);
        }
        
        public string PingMovAdmin(string name) {
            return base.Channel.PingMovAdmin(name);
        }
        
        public string PingSysAdmin(string name) {
            return base.Channel.PingSysAdmin(name);
        }
    }
}
