#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndignadoServer.LinqDataContext
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="IndignadoDB")]
	public partial class IndignadoDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAprobacione(Aprobacione instance);
    partial void UpdateAprobacione(Aprobacione instance);
    partial void DeleteAprobacione(Aprobacione instance);
    partial void InsertUsuario(Usuario instance);
    partial void UpdateUsuario(Usuario instance);
    partial void DeleteUsuario(Usuario instance);
    partial void InsertAsistencia(Asistencia instance);
    partial void UpdateAsistencia(Asistencia instance);
    partial void DeleteAsistencia(Asistencia instance);
    partial void InsertCategoriasTematica(CategoriasTematica instance);
    partial void UpdateCategoriasTematica(CategoriasTematica instance);
    partial void DeleteCategoriasTematica(CategoriasTematica instance);
    partial void InsertCatTemasConvocatoria(CatTemasConvocatoria instance);
    partial void UpdateCatTemasConvocatoria(CatTemasConvocatoria instance);
    partial void DeleteCatTemasConvocatoria(CatTemasConvocatoria instance);
    partial void InsertConvocatoria(Convocatoria instance);
    partial void UpdateConvocatoria(Convocatoria instance);
    partial void DeleteConvocatoria(Convocatoria instance);
    partial void InsertInterese(Interese instance);
    partial void UpdateInterese(Interese instance);
    partial void DeleteInterese(Interese instance);
    partial void InsertLayout(Layout instance);
    partial void UpdateLayout(Layout instance);
    partial void DeleteLayout(Layout instance);
    partial void InsertMarcasInadecuado(MarcasInadecuado instance);
    partial void UpdateMarcasInadecuado(MarcasInadecuado instance);
    partial void DeleteMarcasInadecuado(MarcasInadecuado instance);
    partial void InsertMovimiento(Movimiento instance);
    partial void UpdateMovimiento(Movimiento instance);
    partial void DeleteMovimiento(Movimiento instance);
    partial void InsertRecurso(Recurso instance);
    partial void UpdateRecurso(Recurso instance);
    partial void DeleteRecurso(Recurso instance);
    partial void InsertRssFeed(RssFeed instance);
    partial void UpdateRssFeed(RssFeed instance);
    partial void DeleteRssFeed(RssFeed instance);
    partial void InsertUsuarioFacebook(UsuarioFacebook instance);
    partial void UpdateUsuarioFacebook(UsuarioFacebook instance);
    partial void DeleteUsuarioFacebook(UsuarioFacebook instance);
    #endregion
		
		public IndignadoDBDataContext() : 
				base(global::IndignadoServer.Properties.Settings.Default.IndignadoDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public IndignadoDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public IndignadoDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public IndignadoDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public IndignadoDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Aprobacione> Aprobaciones
		{
			get
			{
				return this.GetTable<Aprobacione>();
			}
		}
		
		public System.Data.Linq.Table<Usuario> Usuarios
		{
			get
			{
				return this.GetTable<Usuario>();
			}
		}
		
		public System.Data.Linq.Table<Asistencia> Asistencias
		{
			get
			{
				return this.GetTable<Asistencia>();
			}
		}
		
		public System.Data.Linq.Table<CategoriasTematica> CategoriasTematicas
		{
			get
			{
				return this.GetTable<CategoriasTematica>();
			}
		}
		
		public System.Data.Linq.Table<CatTemasConvocatoria> CatTemasConvocatorias
		{
			get
			{
				return this.GetTable<CatTemasConvocatoria>();
			}
		}
		
		public System.Data.Linq.Table<Convocatoria> Convocatorias
		{
			get
			{
				return this.GetTable<Convocatoria>();
			}
		}
		
		public System.Data.Linq.Table<Interese> Intereses
		{
			get
			{
				return this.GetTable<Interese>();
			}
		}
		
		public System.Data.Linq.Table<Layout> Layouts
		{
			get
			{
				return this.GetTable<Layout>();
			}
		}
		
		public System.Data.Linq.Table<MarcasInadecuado> MarcasInadecuados
		{
			get
			{
				return this.GetTable<MarcasInadecuado>();
			}
		}
		
		public System.Data.Linq.Table<Movimiento> Movimientos
		{
			get
			{
				return this.GetTable<Movimiento>();
			}
		}
		
		public System.Data.Linq.Table<Recurso> Recursos
		{
			get
			{
				return this.GetTable<Recurso>();
			}
		}
		
		public System.Data.Linq.Table<RssFeed> RssFeeds
		{
			get
			{
				return this.GetTable<RssFeed>();
			}
		}
		
		public System.Data.Linq.Table<UsuarioFacebook> UsuarioFacebooks
		{
			get
			{
				return this.GetTable<UsuarioFacebook>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Aprobaciones")]
	public partial class Aprobacione : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idRecurso;
		
		private int _idUsuario;
		
		private EntityRef<Usuario> _Usuario;
		
		private EntityRef<Recurso> _Recurso;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidRecursoChanging(int value);
    partial void OnidRecursoChanged();
    partial void OnidUsuarioChanging(int value);
    partial void OnidUsuarioChanged();
    #endregion
		
		public Aprobacione()
		{
			this._Usuario = default(EntityRef<Usuario>);
			this._Recurso = default(EntityRef<Recurso>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idRecurso", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idRecurso
		{
			get
			{
				return this._idRecurso;
			}
			set
			{
				if ((this._idRecurso != value))
				{
					if (this._Recurso.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidRecursoChanging(value);
					this.SendPropertyChanging();
					this._idRecurso = value;
					this.SendPropertyChanged("idRecurso");
					this.OnidRecursoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUsuario", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idUsuario
		{
			get
			{
				return this._idUsuario;
			}
			set
			{
				if ((this._idUsuario != value))
				{
					if (this._Usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidUsuarioChanging(value);
					this.SendPropertyChanging();
					this._idUsuario = value;
					this.SendPropertyChanged("idUsuario");
					this.OnidUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Aprobacione", Storage="_Usuario", ThisKey="idUsuario", OtherKey="id", IsForeignKey=true)]
		public Usuario Usuario
		{
			get
			{
				return this._Usuario.Entity;
			}
			set
			{
				Usuario previousValue = this._Usuario.Entity;
				if (((previousValue != value) 
							|| (this._Usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuario.Entity = null;
						previousValue.Aprobaciones.Remove(this);
					}
					this._Usuario.Entity = value;
					if ((value != null))
					{
						value.Aprobaciones.Add(this);
						this._idUsuario = value.id;
					}
					else
					{
						this._idUsuario = default(int);
					}
					this.SendPropertyChanged("Usuario");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Recurso_Aprobacione", Storage="_Recurso", ThisKey="idRecurso", OtherKey="id", IsForeignKey=true)]
		public Recurso Recurso
		{
			get
			{
				return this._Recurso.Entity;
			}
			set
			{
				Recurso previousValue = this._Recurso.Entity;
				if (((previousValue != value) 
							|| (this._Recurso.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Recurso.Entity = null;
						previousValue.Aprobaciones.Remove(this);
					}
					this._Recurso.Entity = value;
					if ((value != null))
					{
						value.Aprobaciones.Add(this);
						this._idRecurso = value.id;
					}
					else
					{
						this._idRecurso = default(int);
					}
					this.SendPropertyChanged("Recurso");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuarios")]
	public partial class Usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _idMovimiento;
		
		private string _nombre;
		
		private string _apodo;
		
		private string _mail;
		
		private System.Data.Linq.Binary _contraseña;
		
		private double _latitud;
		
		private double _longitud;
		
		private System.Nullable<System.DateTime> _fechaRegistro;
		
		private System.Nullable<int> _cantRecursosMarcadosInadecuados;
		
		private System.Nullable<int> _cantRecursosDeshabilitados;
		
		private System.Nullable<bool> _banned;
		
		private short _privilegio;
		
		private EntitySet<Aprobacione> _Aprobaciones;
		
		private EntitySet<Asistencia> _Asistencias;
		
		private EntitySet<Convocatoria> _Convocatorias;
		
		private EntitySet<Interese> _Intereses;
		
		private EntitySet<MarcasInadecuado> _MarcasInadecuados;
		
		private EntityRef<Recurso> _Recurso;
		
		private EntitySet<UsuarioFacebook> _UsuarioFacebooks;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnidMovimientoChanging(int value);
    partial void OnidMovimientoChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnapodoChanging(string value);
    partial void OnapodoChanged();
    partial void OnmailChanging(string value);
    partial void OnmailChanged();
    partial void OncontraseñaChanging(System.Data.Linq.Binary value);
    partial void OncontraseñaChanged();
    partial void OnlatitudChanging(double value);
    partial void OnlatitudChanged();
    partial void OnlongitudChanging(double value);
    partial void OnlongitudChanged();
    partial void OnfechaRegistroChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaRegistroChanged();
    partial void OncantRecursosMarcadosInadecuadosChanging(System.Nullable<int> value);
    partial void OncantRecursosMarcadosInadecuadosChanged();
    partial void OncantRecursosDeshabilitadosChanging(System.Nullable<int> value);
    partial void OncantRecursosDeshabilitadosChanged();
    partial void OnbannedChanging(System.Nullable<bool> value);
    partial void OnbannedChanged();
    partial void OnprivilegioChanging(short value);
    partial void OnprivilegioChanged();
    #endregion
		
		public Usuario()
		{
			this._Aprobaciones = new EntitySet<Aprobacione>(new Action<Aprobacione>(this.attach_Aprobaciones), new Action<Aprobacione>(this.detach_Aprobaciones));
			this._Asistencias = new EntitySet<Asistencia>(new Action<Asistencia>(this.attach_Asistencias), new Action<Asistencia>(this.detach_Asistencias));
			this._Convocatorias = new EntitySet<Convocatoria>(new Action<Convocatoria>(this.attach_Convocatorias), new Action<Convocatoria>(this.detach_Convocatorias));
			this._Intereses = new EntitySet<Interese>(new Action<Interese>(this.attach_Intereses), new Action<Interese>(this.detach_Intereses));
			this._MarcasInadecuados = new EntitySet<MarcasInadecuado>(new Action<MarcasInadecuado>(this.attach_MarcasInadecuados), new Action<MarcasInadecuado>(this.detach_MarcasInadecuados));
			this._Recurso = default(EntityRef<Recurso>);
			this._UsuarioFacebooks = new EntitySet<UsuarioFacebook>(new Action<UsuarioFacebook>(this.attach_UsuarioFacebooks), new Action<UsuarioFacebook>(this.detach_UsuarioFacebooks));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idMovimiento", DbType="Int NOT NULL")]
		public int idMovimiento
		{
			get
			{
				return this._idMovimiento;
			}
			set
			{
				if ((this._idMovimiento != value))
				{
					this.OnidMovimientoChanging(value);
					this.SendPropertyChanging();
					this._idMovimiento = value;
					this.SendPropertyChanged("idMovimiento");
					this.OnidMovimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apodo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string apodo
		{
			get
			{
				return this._apodo;
			}
			set
			{
				if ((this._apodo != value))
				{
					this.OnapodoChanging(value);
					this.SendPropertyChanging();
					this._apodo = value;
					this.SendPropertyChanged("apodo");
					this.OnapodoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mail", DbType="VarChar(50)")]
		public string mail
		{
			get
			{
				return this._mail;
			}
			set
			{
				if ((this._mail != value))
				{
					this.OnmailChanging(value);
					this.SendPropertyChanging();
					this._mail = value;
					this.SendPropertyChanged("mail");
					this.OnmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contraseña", DbType="VarBinary(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary contraseña
		{
			get
			{
				return this._contraseña;
			}
			set
			{
				if ((this._contraseña != value))
				{
					this.OncontraseñaChanging(value);
					this.SendPropertyChanging();
					this._contraseña = value;
					this.SendPropertyChanged("contraseña");
					this.OncontraseñaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_latitud", DbType="Float NOT NULL")]
		public double latitud
		{
			get
			{
				return this._latitud;
			}
			set
			{
				if ((this._latitud != value))
				{
					this.OnlatitudChanging(value);
					this.SendPropertyChanging();
					this._latitud = value;
					this.SendPropertyChanged("latitud");
					this.OnlatitudChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_longitud", DbType="Float NOT NULL")]
		public double longitud
		{
			get
			{
				return this._longitud;
			}
			set
			{
				if ((this._longitud != value))
				{
					this.OnlongitudChanging(value);
					this.SendPropertyChanging();
					this._longitud = value;
					this.SendPropertyChanged("longitud");
					this.OnlongitudChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaRegistro", DbType="DateTime")]
		public System.Nullable<System.DateTime> fechaRegistro
		{
			get
			{
				return this._fechaRegistro;
			}
			set
			{
				if ((this._fechaRegistro != value))
				{
					this.OnfechaRegistroChanging(value);
					this.SendPropertyChanging();
					this._fechaRegistro = value;
					this.SendPropertyChanged("fechaRegistro");
					this.OnfechaRegistroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantRecursosMarcadosInadecuados", DbType="Int")]
		public System.Nullable<int> cantRecursosMarcadosInadecuados
		{
			get
			{
				return this._cantRecursosMarcadosInadecuados;
			}
			set
			{
				if ((this._cantRecursosMarcadosInadecuados != value))
				{
					this.OncantRecursosMarcadosInadecuadosChanging(value);
					this.SendPropertyChanging();
					this._cantRecursosMarcadosInadecuados = value;
					this.SendPropertyChanged("cantRecursosMarcadosInadecuados");
					this.OncantRecursosMarcadosInadecuadosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantRecursosDeshabilitados", DbType="Int")]
		public System.Nullable<int> cantRecursosDeshabilitados
		{
			get
			{
				return this._cantRecursosDeshabilitados;
			}
			set
			{
				if ((this._cantRecursosDeshabilitados != value))
				{
					this.OncantRecursosDeshabilitadosChanging(value);
					this.SendPropertyChanging();
					this._cantRecursosDeshabilitados = value;
					this.SendPropertyChanged("cantRecursosDeshabilitados");
					this.OncantRecursosDeshabilitadosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_banned", DbType="Bit")]
		public System.Nullable<bool> banned
		{
			get
			{
				return this._banned;
			}
			set
			{
				if ((this._banned != value))
				{
					this.OnbannedChanging(value);
					this.SendPropertyChanging();
					this._banned = value;
					this.SendPropertyChanged("banned");
					this.OnbannedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_privilegio", DbType="SmallInt NOT NULL")]
		public short privilegio
		{
			get
			{
				return this._privilegio;
			}
			set
			{
				if ((this._privilegio != value))
				{
					this.OnprivilegioChanging(value);
					this.SendPropertyChanging();
					this._privilegio = value;
					this.SendPropertyChanged("privilegio");
					this.OnprivilegioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Aprobacione", Storage="_Aprobaciones", ThisKey="id", OtherKey="idUsuario")]
		public EntitySet<Aprobacione> Aprobaciones
		{
			get
			{
				return this._Aprobaciones;
			}
			set
			{
				this._Aprobaciones.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Asistencia", Storage="_Asistencias", ThisKey="id", OtherKey="idUsuario")]
		public EntitySet<Asistencia> Asistencias
		{
			get
			{
				return this._Asistencias;
			}
			set
			{
				this._Asistencias.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Convocatoria", Storage="_Convocatorias", ThisKey="id", OtherKey="idAutor")]
		public EntitySet<Convocatoria> Convocatorias
		{
			get
			{
				return this._Convocatorias;
			}
			set
			{
				this._Convocatorias.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Interese", Storage="_Intereses", ThisKey="id", OtherKey="idUsuario")]
		public EntitySet<Interese> Intereses
		{
			get
			{
				return this._Intereses;
			}
			set
			{
				this._Intereses.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_MarcasInadecuado", Storage="_MarcasInadecuados", ThisKey="id", OtherKey="idUsuario")]
		public EntitySet<MarcasInadecuado> MarcasInadecuados
		{
			get
			{
				return this._MarcasInadecuados;
			}
			set
			{
				this._MarcasInadecuados.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Recurso", Storage="_Recurso", ThisKey="id", OtherKey="id", IsUnique=true, IsForeignKey=false)]
		public Recurso Recurso
		{
			get
			{
				return this._Recurso.Entity;
			}
			set
			{
				Recurso previousValue = this._Recurso.Entity;
				if (((previousValue != value) 
							|| (this._Recurso.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Recurso.Entity = null;
						previousValue.Usuario = null;
					}
					this._Recurso.Entity = value;
					if ((value != null))
					{
						value.Usuario = this;
					}
					this.SendPropertyChanged("Recurso");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_UsuarioFacebook", Storage="_UsuarioFacebooks", ThisKey="id", OtherKey="idUsuario")]
		public EntitySet<UsuarioFacebook> UsuarioFacebooks
		{
			get
			{
				return this._UsuarioFacebooks;
			}
			set
			{
				this._UsuarioFacebooks.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Aprobaciones(Aprobacione entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = this;
		}
		
		private void detach_Aprobaciones(Aprobacione entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = null;
		}
		
		private void attach_Asistencias(Asistencia entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = this;
		}
		
		private void detach_Asistencias(Asistencia entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = null;
		}
		
		private void attach_Convocatorias(Convocatoria entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = this;
		}
		
		private void detach_Convocatorias(Convocatoria entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = null;
		}
		
		private void attach_Intereses(Interese entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = this;
		}
		
		private void detach_Intereses(Interese entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = null;
		}
		
		private void attach_MarcasInadecuados(MarcasInadecuado entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = this;
		}
		
		private void detach_MarcasInadecuados(MarcasInadecuado entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = null;
		}
		
		private void attach_UsuarioFacebooks(UsuarioFacebook entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = this;
		}
		
		private void detach_UsuarioFacebooks(UsuarioFacebook entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Asistencias")]
	public partial class Asistencia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idConvocatoria;
		
		private int _idUsuario;
		
		private int _hayAsistencia;
		
		private EntityRef<Usuario> _Usuario;
		
		private EntityRef<Convocatoria> _Convocatoria;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidConvocatoriaChanging(int value);
    partial void OnidConvocatoriaChanged();
    partial void OnidUsuarioChanging(int value);
    partial void OnidUsuarioChanged();
    partial void OnhayAsistenciaChanging(int value);
    partial void OnhayAsistenciaChanged();
    #endregion
		
		public Asistencia()
		{
			this._Usuario = default(EntityRef<Usuario>);
			this._Convocatoria = default(EntityRef<Convocatoria>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idConvocatoria", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idConvocatoria
		{
			get
			{
				return this._idConvocatoria;
			}
			set
			{
				if ((this._idConvocatoria != value))
				{
					if (this._Convocatoria.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidConvocatoriaChanging(value);
					this.SendPropertyChanging();
					this._idConvocatoria = value;
					this.SendPropertyChanged("idConvocatoria");
					this.OnidConvocatoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUsuario", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idUsuario
		{
			get
			{
				return this._idUsuario;
			}
			set
			{
				if ((this._idUsuario != value))
				{
					if (this._Usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidUsuarioChanging(value);
					this.SendPropertyChanging();
					this._idUsuario = value;
					this.SendPropertyChanged("idUsuario");
					this.OnidUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hayAsistencia", DbType="Int NOT NULL")]
		public int hayAsistencia
		{
			get
			{
				return this._hayAsistencia;
			}
			set
			{
				if ((this._hayAsistencia != value))
				{
					this.OnhayAsistenciaChanging(value);
					this.SendPropertyChanging();
					this._hayAsistencia = value;
					this.SendPropertyChanged("hayAsistencia");
					this.OnhayAsistenciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Asistencia", Storage="_Usuario", ThisKey="idUsuario", OtherKey="id", IsForeignKey=true)]
		public Usuario Usuario
		{
			get
			{
				return this._Usuario.Entity;
			}
			set
			{
				Usuario previousValue = this._Usuario.Entity;
				if (((previousValue != value) 
							|| (this._Usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuario.Entity = null;
						previousValue.Asistencias.Remove(this);
					}
					this._Usuario.Entity = value;
					if ((value != null))
					{
						value.Asistencias.Add(this);
						this._idUsuario = value.id;
					}
					else
					{
						this._idUsuario = default(int);
					}
					this.SendPropertyChanged("Usuario");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Convocatoria_Asistencia", Storage="_Convocatoria", ThisKey="idConvocatoria", OtherKey="id", IsForeignKey=true)]
		public Convocatoria Convocatoria
		{
			get
			{
				return this._Convocatoria.Entity;
			}
			set
			{
				Convocatoria previousValue = this._Convocatoria.Entity;
				if (((previousValue != value) 
							|| (this._Convocatoria.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Convocatoria.Entity = null;
						previousValue.Asistencias.Remove(this);
					}
					this._Convocatoria.Entity = value;
					if ((value != null))
					{
						value.Asistencias.Add(this);
						this._idConvocatoria = value.id;
					}
					else
					{
						this._idConvocatoria = default(int);
					}
					this.SendPropertyChanged("Convocatoria");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CategoriasTematicas")]
	public partial class CategoriasTematica : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _idMovimiento;
		
		private string _titulo;
		
		private string _descripcion;
		
		private System.Nullable<int> _miInteres;
		
		private EntitySet<CatTemasConvocatoria> _CatTemasConvocatorias;
		
		private EntitySet<Interese> _Intereses;
		
		private EntityRef<Movimiento> _Movimiento;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnidMovimientoChanging(int value);
    partial void OnidMovimientoChanged();
    partial void OntituloChanging(string value);
    partial void OntituloChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    partial void OnmiInteresChanging(System.Nullable<int> value);
    partial void OnmiInteresChanged();
    #endregion
		
		public CategoriasTematica()
		{
			this._CatTemasConvocatorias = new EntitySet<CatTemasConvocatoria>(new Action<CatTemasConvocatoria>(this.attach_CatTemasConvocatorias), new Action<CatTemasConvocatoria>(this.detach_CatTemasConvocatorias));
			this._Intereses = new EntitySet<Interese>(new Action<Interese>(this.attach_Intereses), new Action<Interese>(this.detach_Intereses));
			this._Movimiento = default(EntityRef<Movimiento>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idMovimiento", DbType="Int NOT NULL")]
		public int idMovimiento
		{
			get
			{
				return this._idMovimiento;
			}
			set
			{
				if ((this._idMovimiento != value))
				{
					if (this._Movimiento.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidMovimientoChanging(value);
					this.SendPropertyChanging();
					this._idMovimiento = value;
					this.SendPropertyChanged("idMovimiento");
					this.OnidMovimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_titulo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string titulo
		{
			get
			{
				return this._titulo;
			}
			set
			{
				if ((this._titulo != value))
				{
					this.OntituloChanging(value);
					this.SendPropertyChanging();
					this._titulo = value;
					this.SendPropertyChanged("titulo");
					this.OntituloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(100)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_miInteres", DbType="Int")]
		public System.Nullable<int> miInteres
		{
			get
			{
				return this._miInteres;
			}
			set
			{
				if ((this._miInteres != value))
				{
					this.OnmiInteresChanging(value);
					this.SendPropertyChanging();
					this._miInteres = value;
					this.SendPropertyChanged("miInteres");
					this.OnmiInteresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CategoriasTematica_CatTemasConvocatoria", Storage="_CatTemasConvocatorias", ThisKey="id", OtherKey="idCategoriaTematica")]
		public EntitySet<CatTemasConvocatoria> CatTemasConvocatorias
		{
			get
			{
				return this._CatTemasConvocatorias;
			}
			set
			{
				this._CatTemasConvocatorias.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CategoriasTematica_Interese", Storage="_Intereses", ThisKey="id", OtherKey="idCategoriaTematica")]
		public EntitySet<Interese> Intereses
		{
			get
			{
				return this._Intereses;
			}
			set
			{
				this._Intereses.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Movimiento_CategoriasTematica", Storage="_Movimiento", ThisKey="idMovimiento", OtherKey="id", IsForeignKey=true)]
		public Movimiento Movimiento
		{
			get
			{
				return this._Movimiento.Entity;
			}
			set
			{
				Movimiento previousValue = this._Movimiento.Entity;
				if (((previousValue != value) 
							|| (this._Movimiento.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Movimiento.Entity = null;
						previousValue.CategoriasTematicas.Remove(this);
					}
					this._Movimiento.Entity = value;
					if ((value != null))
					{
						value.CategoriasTematicas.Add(this);
						this._idMovimiento = value.id;
					}
					else
					{
						this._idMovimiento = default(int);
					}
					this.SendPropertyChanged("Movimiento");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CatTemasConvocatorias(CatTemasConvocatoria entity)
		{
			this.SendPropertyChanging();
			entity.CategoriasTematica = this;
		}
		
		private void detach_CatTemasConvocatorias(CatTemasConvocatoria entity)
		{
			this.SendPropertyChanging();
			entity.CategoriasTematica = null;
		}
		
		private void attach_Intereses(Interese entity)
		{
			this.SendPropertyChanging();
			entity.CategoriasTematica = this;
		}
		
		private void detach_Intereses(Interese entity)
		{
			this.SendPropertyChanging();
			entity.CategoriasTematica = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CatTemasConvocatorias")]
	public partial class CatTemasConvocatoria : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idCategoriaTematica;
		
		private int _idConvocatoria;
		
		private EntityRef<CategoriasTematica> _CategoriasTematica;
		
		private EntityRef<Convocatoria> _Convocatoria;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidCategoriaTematicaChanging(int value);
    partial void OnidCategoriaTematicaChanged();
    partial void OnidConvocatoriaChanging(int value);
    partial void OnidConvocatoriaChanged();
    #endregion
		
		public CatTemasConvocatoria()
		{
			this._CategoriasTematica = default(EntityRef<CategoriasTematica>);
			this._Convocatoria = default(EntityRef<Convocatoria>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCategoriaTematica", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idCategoriaTematica
		{
			get
			{
				return this._idCategoriaTematica;
			}
			set
			{
				if ((this._idCategoriaTematica != value))
				{
					if (this._CategoriasTematica.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidCategoriaTematicaChanging(value);
					this.SendPropertyChanging();
					this._idCategoriaTematica = value;
					this.SendPropertyChanged("idCategoriaTematica");
					this.OnidCategoriaTematicaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idConvocatoria", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idConvocatoria
		{
			get
			{
				return this._idConvocatoria;
			}
			set
			{
				if ((this._idConvocatoria != value))
				{
					if (this._Convocatoria.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidConvocatoriaChanging(value);
					this.SendPropertyChanging();
					this._idConvocatoria = value;
					this.SendPropertyChanged("idConvocatoria");
					this.OnidConvocatoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CategoriasTematica_CatTemasConvocatoria", Storage="_CategoriasTematica", ThisKey="idCategoriaTematica", OtherKey="id", IsForeignKey=true)]
		public CategoriasTematica CategoriasTematica
		{
			get
			{
				return this._CategoriasTematica.Entity;
			}
			set
			{
				CategoriasTematica previousValue = this._CategoriasTematica.Entity;
				if (((previousValue != value) 
							|| (this._CategoriasTematica.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CategoriasTematica.Entity = null;
						previousValue.CatTemasConvocatorias.Remove(this);
					}
					this._CategoriasTematica.Entity = value;
					if ((value != null))
					{
						value.CatTemasConvocatorias.Add(this);
						this._idCategoriaTematica = value.id;
					}
					else
					{
						this._idCategoriaTematica = default(int);
					}
					this.SendPropertyChanged("CategoriasTematica");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Convocatoria_CatTemasConvocatoria", Storage="_Convocatoria", ThisKey="idConvocatoria", OtherKey="id", IsForeignKey=true)]
		public Convocatoria Convocatoria
		{
			get
			{
				return this._Convocatoria.Entity;
			}
			set
			{
				Convocatoria previousValue = this._Convocatoria.Entity;
				if (((previousValue != value) 
							|| (this._Convocatoria.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Convocatoria.Entity = null;
						previousValue.CatTemasConvocatorias.Remove(this);
					}
					this._Convocatoria.Entity = value;
					if ((value != null))
					{
						value.CatTemasConvocatorias.Add(this);
						this._idConvocatoria = value.id;
					}
					else
					{
						this._idConvocatoria = default(int);
					}
					this.SendPropertyChanged("Convocatoria");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Convocatorias")]
	public partial class Convocatoria : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _idMovimiento;
		
		private int _idAutor;
		
		private string _titulo;
		
		private string _descripcion;
		
		private string _logo;
		
		private double _latitud;
		
		private double _longitud;
		
		private System.Nullable<System.DateTime> _fechaInicio;
		
		private System.Nullable<System.DateTime> _fechaFin;
		
		private System.Nullable<int> _minQuorum;
		
		private System.Nullable<int> _cantAsistencias;
		
		private System.Nullable<int> _miAsistencia;
		
		private EntitySet<Asistencia> _Asistencias;
		
		private EntitySet<CatTemasConvocatoria> _CatTemasConvocatorias;
		
		private EntityRef<Usuario> _Usuario;
		
		private EntityRef<Movimiento> _Movimiento;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnidMovimientoChanging(int value);
    partial void OnidMovimientoChanged();
    partial void OnidAutorChanging(int value);
    partial void OnidAutorChanged();
    partial void OntituloChanging(string value);
    partial void OntituloChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    partial void OnlogoChanging(string value);
    partial void OnlogoChanged();
    partial void OnlatitudChanging(double value);
    partial void OnlatitudChanged();
    partial void OnlongitudChanging(double value);
    partial void OnlongitudChanged();
    partial void OnfechaInicioChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaInicioChanged();
    partial void OnfechaFinChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaFinChanged();
    partial void OnminQuorumChanging(System.Nullable<int> value);
    partial void OnminQuorumChanged();
    partial void OncantAsistenciasChanging(System.Nullable<int> value);
    partial void OncantAsistenciasChanged();
    partial void OnmiAsistenciaChanging(System.Nullable<int> value);
    partial void OnmiAsistenciaChanged();
    #endregion
		
		public Convocatoria()
		{
			this._Asistencias = new EntitySet<Asistencia>(new Action<Asistencia>(this.attach_Asistencias), new Action<Asistencia>(this.detach_Asistencias));
			this._CatTemasConvocatorias = new EntitySet<CatTemasConvocatoria>(new Action<CatTemasConvocatoria>(this.attach_CatTemasConvocatorias), new Action<CatTemasConvocatoria>(this.detach_CatTemasConvocatorias));
			this._Usuario = default(EntityRef<Usuario>);
			this._Movimiento = default(EntityRef<Movimiento>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idMovimiento", DbType="Int NOT NULL")]
		public int idMovimiento
		{
			get
			{
				return this._idMovimiento;
			}
			set
			{
				if ((this._idMovimiento != value))
				{
					if (this._Movimiento.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidMovimientoChanging(value);
					this.SendPropertyChanging();
					this._idMovimiento = value;
					this.SendPropertyChanged("idMovimiento");
					this.OnidMovimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idAutor", DbType="Int NOT NULL")]
		public int idAutor
		{
			get
			{
				return this._idAutor;
			}
			set
			{
				if ((this._idAutor != value))
				{
					if (this._Usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidAutorChanging(value);
					this.SendPropertyChanging();
					this._idAutor = value;
					this.SendPropertyChanged("idAutor");
					this.OnidAutorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_titulo", DbType="VarChar(50)")]
		public string titulo
		{
			get
			{
				return this._titulo;
			}
			set
			{
				if ((this._titulo != value))
				{
					this.OntituloChanging(value);
					this.SendPropertyChanging();
					this._titulo = value;
					this.SendPropertyChanged("titulo");
					this.OntituloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(50)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_logo", DbType="VarChar(MAX)")]
		public string logo
		{
			get
			{
				return this._logo;
			}
			set
			{
				if ((this._logo != value))
				{
					this.OnlogoChanging(value);
					this.SendPropertyChanging();
					this._logo = value;
					this.SendPropertyChanged("logo");
					this.OnlogoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_latitud", DbType="Float NOT NULL")]
		public double latitud
		{
			get
			{
				return this._latitud;
			}
			set
			{
				if ((this._latitud != value))
				{
					this.OnlatitudChanging(value);
					this.SendPropertyChanging();
					this._latitud = value;
					this.SendPropertyChanged("latitud");
					this.OnlatitudChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_longitud", DbType="Float NOT NULL")]
		public double longitud
		{
			get
			{
				return this._longitud;
			}
			set
			{
				if ((this._longitud != value))
				{
					this.OnlongitudChanging(value);
					this.SendPropertyChanging();
					this._longitud = value;
					this.SendPropertyChanged("longitud");
					this.OnlongitudChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaInicio", DbType="DateTime")]
		public System.Nullable<System.DateTime> fechaInicio
		{
			get
			{
				return this._fechaInicio;
			}
			set
			{
				if ((this._fechaInicio != value))
				{
					this.OnfechaInicioChanging(value);
					this.SendPropertyChanging();
					this._fechaInicio = value;
					this.SendPropertyChanged("fechaInicio");
					this.OnfechaInicioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaFin", DbType="DateTime")]
		public System.Nullable<System.DateTime> fechaFin
		{
			get
			{
				return this._fechaFin;
			}
			set
			{
				if ((this._fechaFin != value))
				{
					this.OnfechaFinChanging(value);
					this.SendPropertyChanging();
					this._fechaFin = value;
					this.SendPropertyChanged("fechaFin");
					this.OnfechaFinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_minQuorum", DbType="Int")]
		public System.Nullable<int> minQuorum
		{
			get
			{
				return this._minQuorum;
			}
			set
			{
				if ((this._minQuorum != value))
				{
					this.OnminQuorumChanging(value);
					this.SendPropertyChanging();
					this._minQuorum = value;
					this.SendPropertyChanged("minQuorum");
					this.OnminQuorumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantAsistencias", DbType="Int")]
		public System.Nullable<int> cantAsistencias
		{
			get
			{
				return this._cantAsistencias;
			}
			set
			{
				if ((this._cantAsistencias != value))
				{
					this.OncantAsistenciasChanging(value);
					this.SendPropertyChanging();
					this._cantAsistencias = value;
					this.SendPropertyChanged("cantAsistencias");
					this.OncantAsistenciasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_miAsistencia", DbType="Int")]
		public System.Nullable<int> miAsistencia
		{
			get
			{
				return this._miAsistencia;
			}
			set
			{
				if ((this._miAsistencia != value))
				{
					this.OnmiAsistenciaChanging(value);
					this.SendPropertyChanging();
					this._miAsistencia = value;
					this.SendPropertyChanged("miAsistencia");
					this.OnmiAsistenciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Convocatoria_Asistencia", Storage="_Asistencias", ThisKey="id", OtherKey="idConvocatoria")]
		public EntitySet<Asistencia> Asistencias
		{
			get
			{
				return this._Asistencias;
			}
			set
			{
				this._Asistencias.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Convocatoria_CatTemasConvocatoria", Storage="_CatTemasConvocatorias", ThisKey="id", OtherKey="idConvocatoria")]
		public EntitySet<CatTemasConvocatoria> CatTemasConvocatorias
		{
			get
			{
				return this._CatTemasConvocatorias;
			}
			set
			{
				this._CatTemasConvocatorias.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Convocatoria", Storage="_Usuario", ThisKey="idAutor", OtherKey="id", IsForeignKey=true)]
		public Usuario Usuario
		{
			get
			{
				return this._Usuario.Entity;
			}
			set
			{
				Usuario previousValue = this._Usuario.Entity;
				if (((previousValue != value) 
							|| (this._Usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuario.Entity = null;
						previousValue.Convocatorias.Remove(this);
					}
					this._Usuario.Entity = value;
					if ((value != null))
					{
						value.Convocatorias.Add(this);
						this._idAutor = value.id;
					}
					else
					{
						this._idAutor = default(int);
					}
					this.SendPropertyChanged("Usuario");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Movimiento_Convocatoria", Storage="_Movimiento", ThisKey="idMovimiento", OtherKey="id", IsForeignKey=true)]
		public Movimiento Movimiento
		{
			get
			{
				return this._Movimiento.Entity;
			}
			set
			{
				Movimiento previousValue = this._Movimiento.Entity;
				if (((previousValue != value) 
							|| (this._Movimiento.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Movimiento.Entity = null;
						previousValue.Convocatorias.Remove(this);
					}
					this._Movimiento.Entity = value;
					if ((value != null))
					{
						value.Convocatorias.Add(this);
						this._idMovimiento = value.id;
					}
					else
					{
						this._idMovimiento = default(int);
					}
					this.SendPropertyChanged("Movimiento");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Asistencias(Asistencia entity)
		{
			this.SendPropertyChanging();
			entity.Convocatoria = this;
		}
		
		private void detach_Asistencias(Asistencia entity)
		{
			this.SendPropertyChanging();
			entity.Convocatoria = null;
		}
		
		private void attach_CatTemasConvocatorias(CatTemasConvocatoria entity)
		{
			this.SendPropertyChanging();
			entity.Convocatoria = this;
		}
		
		private void detach_CatTemasConvocatorias(CatTemasConvocatoria entity)
		{
			this.SendPropertyChanging();
			entity.Convocatoria = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Intereses")]
	public partial class Interese : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idCategoriaTematica;
		
		private int _idUsuario;
		
		private EntityRef<CategoriasTematica> _CategoriasTematica;
		
		private EntityRef<Usuario> _Usuario;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidCategoriaTematicaChanging(int value);
    partial void OnidCategoriaTematicaChanged();
    partial void OnidUsuarioChanging(int value);
    partial void OnidUsuarioChanged();
    #endregion
		
		public Interese()
		{
			this._CategoriasTematica = default(EntityRef<CategoriasTematica>);
			this._Usuario = default(EntityRef<Usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCategoriaTematica", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idCategoriaTematica
		{
			get
			{
				return this._idCategoriaTematica;
			}
			set
			{
				if ((this._idCategoriaTematica != value))
				{
					if (this._CategoriasTematica.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidCategoriaTematicaChanging(value);
					this.SendPropertyChanging();
					this._idCategoriaTematica = value;
					this.SendPropertyChanged("idCategoriaTematica");
					this.OnidCategoriaTematicaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUsuario", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idUsuario
		{
			get
			{
				return this._idUsuario;
			}
			set
			{
				if ((this._idUsuario != value))
				{
					if (this._Usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidUsuarioChanging(value);
					this.SendPropertyChanging();
					this._idUsuario = value;
					this.SendPropertyChanged("idUsuario");
					this.OnidUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CategoriasTematica_Interese", Storage="_CategoriasTematica", ThisKey="idCategoriaTematica", OtherKey="id", IsForeignKey=true)]
		public CategoriasTematica CategoriasTematica
		{
			get
			{
				return this._CategoriasTematica.Entity;
			}
			set
			{
				CategoriasTematica previousValue = this._CategoriasTematica.Entity;
				if (((previousValue != value) 
							|| (this._CategoriasTematica.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CategoriasTematica.Entity = null;
						previousValue.Intereses.Remove(this);
					}
					this._CategoriasTematica.Entity = value;
					if ((value != null))
					{
						value.Intereses.Add(this);
						this._idCategoriaTematica = value.id;
					}
					else
					{
						this._idCategoriaTematica = default(int);
					}
					this.SendPropertyChanged("CategoriasTematica");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Interese", Storage="_Usuario", ThisKey="idUsuario", OtherKey="id", IsForeignKey=true)]
		public Usuario Usuario
		{
			get
			{
				return this._Usuario.Entity;
			}
			set
			{
				Usuario previousValue = this._Usuario.Entity;
				if (((previousValue != value) 
							|| (this._Usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuario.Entity = null;
						previousValue.Intereses.Remove(this);
					}
					this._Usuario.Entity = value;
					if ((value != null))
					{
						value.Intereses.Add(this);
						this._idUsuario = value.id;
					}
					else
					{
						this._idUsuario = default(int);
					}
					this.SendPropertyChanged("Usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Layouts")]
	public partial class Layout : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _layoutFile;
		
		private EntitySet<Movimiento> _Movimientos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnlayoutFileChanging(string value);
    partial void OnlayoutFileChanged();
    #endregion
		
		public Layout()
		{
			this._Movimientos = new EntitySet<Movimiento>(new Action<Movimiento>(this.attach_Movimientos), new Action<Movimiento>(this.detach_Movimientos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_layoutFile", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string layoutFile
		{
			get
			{
				return this._layoutFile;
			}
			set
			{
				if ((this._layoutFile != value))
				{
					this.OnlayoutFileChanging(value);
					this.SendPropertyChanging();
					this._layoutFile = value;
					this.SendPropertyChanged("layoutFile");
					this.OnlayoutFileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Layout_Movimiento", Storage="_Movimientos", ThisKey="id", OtherKey="idLayout")]
		public EntitySet<Movimiento> Movimientos
		{
			get
			{
				return this._Movimientos;
			}
			set
			{
				this._Movimientos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Movimientos(Movimiento entity)
		{
			this.SendPropertyChanging();
			entity.Layout = this;
		}
		
		private void detach_Movimientos(Movimiento entity)
		{
			this.SendPropertyChanging();
			entity.Layout = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MarcasInadecuados")]
	public partial class MarcasInadecuado : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idRecurso;
		
		private int _idUsuario;
		
		private EntityRef<Usuario> _Usuario;
		
		private EntityRef<Recurso> _Recurso;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidRecursoChanging(int value);
    partial void OnidRecursoChanged();
    partial void OnidUsuarioChanging(int value);
    partial void OnidUsuarioChanged();
    #endregion
		
		public MarcasInadecuado()
		{
			this._Usuario = default(EntityRef<Usuario>);
			this._Recurso = default(EntityRef<Recurso>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idRecurso", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idRecurso
		{
			get
			{
				return this._idRecurso;
			}
			set
			{
				if ((this._idRecurso != value))
				{
					if (this._Recurso.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidRecursoChanging(value);
					this.SendPropertyChanging();
					this._idRecurso = value;
					this.SendPropertyChanged("idRecurso");
					this.OnidRecursoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUsuario", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idUsuario
		{
			get
			{
				return this._idUsuario;
			}
			set
			{
				if ((this._idUsuario != value))
				{
					if (this._Usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidUsuarioChanging(value);
					this.SendPropertyChanging();
					this._idUsuario = value;
					this.SendPropertyChanged("idUsuario");
					this.OnidUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_MarcasInadecuado", Storage="_Usuario", ThisKey="idUsuario", OtherKey="id", IsForeignKey=true)]
		public Usuario Usuario
		{
			get
			{
				return this._Usuario.Entity;
			}
			set
			{
				Usuario previousValue = this._Usuario.Entity;
				if (((previousValue != value) 
							|| (this._Usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuario.Entity = null;
						previousValue.MarcasInadecuados.Remove(this);
					}
					this._Usuario.Entity = value;
					if ((value != null))
					{
						value.MarcasInadecuados.Add(this);
						this._idUsuario = value.id;
					}
					else
					{
						this._idUsuario = default(int);
					}
					this.SendPropertyChanged("Usuario");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Recurso_MarcasInadecuado", Storage="_Recurso", ThisKey="idRecurso", OtherKey="id", IsForeignKey=true)]
		public Recurso Recurso
		{
			get
			{
				return this._Recurso.Entity;
			}
			set
			{
				Recurso previousValue = this._Recurso.Entity;
				if (((previousValue != value) 
							|| (this._Recurso.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Recurso.Entity = null;
						previousValue.MarcasInadecuados.Remove(this);
					}
					this._Recurso.Entity = value;
					if ((value != null))
					{
						value.MarcasInadecuados.Add(this);
						this._idRecurso = value.id;
					}
					else
					{
						this._idRecurso = default(int);
					}
					this.SendPropertyChanged("Recurso");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Movimiento")]
	public partial class Movimiento : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _nombre;
		
		private bool _habilitado;
		
		private string _logo;
		
		private int _idLayout;
		
		private string _descripcion;
		
		private double _latitud;
		
		private double _longitud;
		
		private System.Nullable<int> _maxMarcasInadecuadasRecursoX;
		
		private System.Nullable<int> _maxRecursosInadecuadosUsuarioZ;
		
		private System.Nullable<int> _maxRecursosPopularesN;
		
		private System.Nullable<int> _maxUltimosRecursosM;
		
		private EntitySet<CategoriasTematica> _CategoriasTematicas;
		
		private EntitySet<Convocatoria> _Convocatorias;
		
		private EntitySet<RssFeed> _RssFeeds;
		
		private EntityRef<Layout> _Layout;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnhabilitadoChanging(bool value);
    partial void OnhabilitadoChanged();
    partial void OnlogoChanging(string value);
    partial void OnlogoChanged();
    partial void OnidLayoutChanging(int value);
    partial void OnidLayoutChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    partial void OnlatitudChanging(double value);
    partial void OnlatitudChanged();
    partial void OnlongitudChanging(double value);
    partial void OnlongitudChanged();
    partial void OnmaxMarcasInadecuadasRecursoXChanging(System.Nullable<int> value);
    partial void OnmaxMarcasInadecuadasRecursoXChanged();
    partial void OnmaxRecursosInadecuadosUsuarioZChanging(System.Nullable<int> value);
    partial void OnmaxRecursosInadecuadosUsuarioZChanged();
    partial void OnmaxRecursosPopularesNChanging(System.Nullable<int> value);
    partial void OnmaxRecursosPopularesNChanged();
    partial void OnmaxUltimosRecursosMChanging(System.Nullable<int> value);
    partial void OnmaxUltimosRecursosMChanged();
    #endregion
		
		public Movimiento()
		{
			this._CategoriasTematicas = new EntitySet<CategoriasTematica>(new Action<CategoriasTematica>(this.attach_CategoriasTematicas), new Action<CategoriasTematica>(this.detach_CategoriasTematicas));
			this._Convocatorias = new EntitySet<Convocatoria>(new Action<Convocatoria>(this.attach_Convocatorias), new Action<Convocatoria>(this.detach_Convocatorias));
			this._RssFeeds = new EntitySet<RssFeed>(new Action<RssFeed>(this.attach_RssFeeds), new Action<RssFeed>(this.detach_RssFeeds));
			this._Layout = default(EntityRef<Layout>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_habilitado", DbType="Bit NOT NULL")]
		public bool habilitado
		{
			get
			{
				return this._habilitado;
			}
			set
			{
				if ((this._habilitado != value))
				{
					this.OnhabilitadoChanging(value);
					this.SendPropertyChanging();
					this._habilitado = value;
					this.SendPropertyChanged("habilitado");
					this.OnhabilitadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_logo", DbType="VarChar(MAX)")]
		public string logo
		{
			get
			{
				return this._logo;
			}
			set
			{
				if ((this._logo != value))
				{
					this.OnlogoChanging(value);
					this.SendPropertyChanging();
					this._logo = value;
					this.SendPropertyChanged("logo");
					this.OnlogoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idLayout", DbType="Int NOT NULL")]
		public int idLayout
		{
			get
			{
				return this._idLayout;
			}
			set
			{
				if ((this._idLayout != value))
				{
					if (this._Layout.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidLayoutChanging(value);
					this.SendPropertyChanging();
					this._idLayout = value;
					this.SendPropertyChanged("idLayout");
					this.OnidLayoutChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(MAX)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_latitud", DbType="Float NOT NULL")]
		public double latitud
		{
			get
			{
				return this._latitud;
			}
			set
			{
				if ((this._latitud != value))
				{
					this.OnlatitudChanging(value);
					this.SendPropertyChanging();
					this._latitud = value;
					this.SendPropertyChanged("latitud");
					this.OnlatitudChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_longitud", DbType="Float NOT NULL")]
		public double longitud
		{
			get
			{
				return this._longitud;
			}
			set
			{
				if ((this._longitud != value))
				{
					this.OnlongitudChanging(value);
					this.SendPropertyChanging();
					this._longitud = value;
					this.SendPropertyChanged("longitud");
					this.OnlongitudChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maxMarcasInadecuadasRecursoX", DbType="Int")]
		public System.Nullable<int> maxMarcasInadecuadasRecursoX
		{
			get
			{
				return this._maxMarcasInadecuadasRecursoX;
			}
			set
			{
				if ((this._maxMarcasInadecuadasRecursoX != value))
				{
					this.OnmaxMarcasInadecuadasRecursoXChanging(value);
					this.SendPropertyChanging();
					this._maxMarcasInadecuadasRecursoX = value;
					this.SendPropertyChanged("maxMarcasInadecuadasRecursoX");
					this.OnmaxMarcasInadecuadasRecursoXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maxRecursosInadecuadosUsuarioZ", DbType="Int")]
		public System.Nullable<int> maxRecursosInadecuadosUsuarioZ
		{
			get
			{
				return this._maxRecursosInadecuadosUsuarioZ;
			}
			set
			{
				if ((this._maxRecursosInadecuadosUsuarioZ != value))
				{
					this.OnmaxRecursosInadecuadosUsuarioZChanging(value);
					this.SendPropertyChanging();
					this._maxRecursosInadecuadosUsuarioZ = value;
					this.SendPropertyChanged("maxRecursosInadecuadosUsuarioZ");
					this.OnmaxRecursosInadecuadosUsuarioZChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maxRecursosPopularesN", DbType="Int")]
		public System.Nullable<int> maxRecursosPopularesN
		{
			get
			{
				return this._maxRecursosPopularesN;
			}
			set
			{
				if ((this._maxRecursosPopularesN != value))
				{
					this.OnmaxRecursosPopularesNChanging(value);
					this.SendPropertyChanging();
					this._maxRecursosPopularesN = value;
					this.SendPropertyChanged("maxRecursosPopularesN");
					this.OnmaxRecursosPopularesNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maxUltimosRecursosM", DbType="Int")]
		public System.Nullable<int> maxUltimosRecursosM
		{
			get
			{
				return this._maxUltimosRecursosM;
			}
			set
			{
				if ((this._maxUltimosRecursosM != value))
				{
					this.OnmaxUltimosRecursosMChanging(value);
					this.SendPropertyChanging();
					this._maxUltimosRecursosM = value;
					this.SendPropertyChanged("maxUltimosRecursosM");
					this.OnmaxUltimosRecursosMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Movimiento_CategoriasTematica", Storage="_CategoriasTematicas", ThisKey="id", OtherKey="idMovimiento")]
		public EntitySet<CategoriasTematica> CategoriasTematicas
		{
			get
			{
				return this._CategoriasTematicas;
			}
			set
			{
				this._CategoriasTematicas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Movimiento_Convocatoria", Storage="_Convocatorias", ThisKey="id", OtherKey="idMovimiento")]
		public EntitySet<Convocatoria> Convocatorias
		{
			get
			{
				return this._Convocatorias;
			}
			set
			{
				this._Convocatorias.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Movimiento_RssFeed", Storage="_RssFeeds", ThisKey="id", OtherKey="idMovimiento")]
		public EntitySet<RssFeed> RssFeeds
		{
			get
			{
				return this._RssFeeds;
			}
			set
			{
				this._RssFeeds.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Layout_Movimiento", Storage="_Layout", ThisKey="idLayout", OtherKey="id", IsForeignKey=true)]
		public Layout Layout
		{
			get
			{
				return this._Layout.Entity;
			}
			set
			{
				Layout previousValue = this._Layout.Entity;
				if (((previousValue != value) 
							|| (this._Layout.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Layout.Entity = null;
						previousValue.Movimientos.Remove(this);
					}
					this._Layout.Entity = value;
					if ((value != null))
					{
						value.Movimientos.Add(this);
						this._idLayout = value.id;
					}
					else
					{
						this._idLayout = default(int);
					}
					this.SendPropertyChanged("Layout");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CategoriasTematicas(CategoriasTematica entity)
		{
			this.SendPropertyChanging();
			entity.Movimiento = this;
		}
		
		private void detach_CategoriasTematicas(CategoriasTematica entity)
		{
			this.SendPropertyChanging();
			entity.Movimiento = null;
		}
		
		private void attach_Convocatorias(Convocatoria entity)
		{
			this.SendPropertyChanging();
			entity.Movimiento = this;
		}
		
		private void detach_Convocatorias(Convocatoria entity)
		{
			this.SendPropertyChanging();
			entity.Movimiento = null;
		}
		
		private void attach_RssFeeds(RssFeed entity)
		{
			this.SendPropertyChanging();
			entity.Movimiento = this;
		}
		
		private void detach_RssFeeds(RssFeed entity)
		{
			this.SendPropertyChanging();
			entity.Movimiento = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Recursos")]
	public partial class Recurso : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _idUsuario;
		
		private string _apodoUsuario;
		
		private string _titulo;
		
		private string _descripcion;
		
		private System.Nullable<System.DateTime> _fecha;
		
		private System.Nullable<int> _tipo;
		
		private string _urlLink;
		
		private string _urlImage;
		
		private string _urlVideo;
		
		private string _urlThumb;
		
		private System.Nullable<int> _cantAprobaciones;
		
		private System.Nullable<int> _meGusta;
		
		private System.Nullable<int> _cantMarcasInadecuado;
		
		private System.Nullable<int> _yoMarqueInadecuado;
		
		private System.Nullable<int> _deshabilitado;
		
		private EntitySet<Aprobacione> _Aprobaciones;
		
		private EntitySet<MarcasInadecuado> _MarcasInadecuados;
		
		private EntityRef<Usuario> _Usuario;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnidUsuarioChanging(int value);
    partial void OnidUsuarioChanged();
    partial void OnapodoUsuarioChanging(string value);
    partial void OnapodoUsuarioChanged();
    partial void OntituloChanging(string value);
    partial void OntituloChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    partial void OnfechaChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaChanged();
    partial void OntipoChanging(System.Nullable<int> value);
    partial void OntipoChanged();
    partial void OnurlLinkChanging(string value);
    partial void OnurlLinkChanged();
    partial void OnurlImageChanging(string value);
    partial void OnurlImageChanged();
    partial void OnurlVideoChanging(string value);
    partial void OnurlVideoChanged();
    partial void OnurlThumbChanging(string value);
    partial void OnurlThumbChanged();
    partial void OncantAprobacionesChanging(System.Nullable<int> value);
    partial void OncantAprobacionesChanged();
    partial void OnmeGustaChanging(System.Nullable<int> value);
    partial void OnmeGustaChanged();
    partial void OncantMarcasInadecuadoChanging(System.Nullable<int> value);
    partial void OncantMarcasInadecuadoChanged();
    partial void OnyoMarqueInadecuadoChanging(System.Nullable<int> value);
    partial void OnyoMarqueInadecuadoChanged();
    partial void OndeshabilitadoChanging(System.Nullable<int> value);
    partial void OndeshabilitadoChanged();
    #endregion
		
		public Recurso()
		{
			this._Aprobaciones = new EntitySet<Aprobacione>(new Action<Aprobacione>(this.attach_Aprobaciones), new Action<Aprobacione>(this.detach_Aprobaciones));
			this._MarcasInadecuados = new EntitySet<MarcasInadecuado>(new Action<MarcasInadecuado>(this.attach_MarcasInadecuados), new Action<MarcasInadecuado>(this.detach_MarcasInadecuados));
			this._Usuario = default(EntityRef<Usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					if (this._Usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUsuario", DbType="Int NOT NULL")]
		public int idUsuario
		{
			get
			{
				return this._idUsuario;
			}
			set
			{
				if ((this._idUsuario != value))
				{
					this.OnidUsuarioChanging(value);
					this.SendPropertyChanging();
					this._idUsuario = value;
					this.SendPropertyChanged("idUsuario");
					this.OnidUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apodoUsuario", DbType="VarChar(50)")]
		public string apodoUsuario
		{
			get
			{
				return this._apodoUsuario;
			}
			set
			{
				if ((this._apodoUsuario != value))
				{
					this.OnapodoUsuarioChanging(value);
					this.SendPropertyChanging();
					this._apodoUsuario = value;
					this.SendPropertyChanged("apodoUsuario");
					this.OnapodoUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_titulo", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string titulo
		{
			get
			{
				return this._titulo;
			}
			set
			{
				if ((this._titulo != value))
				{
					this.OntituloChanging(value);
					this.SendPropertyChanging();
					this._titulo = value;
					this.SendPropertyChanged("titulo");
					this.OntituloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this.OnfechaChanging(value);
					this.SendPropertyChanging();
					this._fecha = value;
					this.SendPropertyChanged("fecha");
					this.OnfechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo", DbType="Int")]
		public System.Nullable<int> tipo
		{
			get
			{
				return this._tipo;
			}
			set
			{
				if ((this._tipo != value))
				{
					this.OntipoChanging(value);
					this.SendPropertyChanging();
					this._tipo = value;
					this.SendPropertyChanged("tipo");
					this.OntipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_urlLink", DbType="VarChar(MAX)")]
		public string urlLink
		{
			get
			{
				return this._urlLink;
			}
			set
			{
				if ((this._urlLink != value))
				{
					this.OnurlLinkChanging(value);
					this.SendPropertyChanging();
					this._urlLink = value;
					this.SendPropertyChanged("urlLink");
					this.OnurlLinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_urlImage", DbType="VarChar(MAX)")]
		public string urlImage
		{
			get
			{
				return this._urlImage;
			}
			set
			{
				if ((this._urlImage != value))
				{
					this.OnurlImageChanging(value);
					this.SendPropertyChanging();
					this._urlImage = value;
					this.SendPropertyChanged("urlImage");
					this.OnurlImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_urlVideo", DbType="VarChar(MAX)")]
		public string urlVideo
		{
			get
			{
				return this._urlVideo;
			}
			set
			{
				if ((this._urlVideo != value))
				{
					this.OnurlVideoChanging(value);
					this.SendPropertyChanging();
					this._urlVideo = value;
					this.SendPropertyChanged("urlVideo");
					this.OnurlVideoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_urlThumb", DbType="VarChar(MAX)")]
		public string urlThumb
		{
			get
			{
				return this._urlThumb;
			}
			set
			{
				if ((this._urlThumb != value))
				{
					this.OnurlThumbChanging(value);
					this.SendPropertyChanging();
					this._urlThumb = value;
					this.SendPropertyChanged("urlThumb");
					this.OnurlThumbChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantAprobaciones", DbType="Int")]
		public System.Nullable<int> cantAprobaciones
		{
			get
			{
				return this._cantAprobaciones;
			}
			set
			{
				if ((this._cantAprobaciones != value))
				{
					this.OncantAprobacionesChanging(value);
					this.SendPropertyChanging();
					this._cantAprobaciones = value;
					this.SendPropertyChanged("cantAprobaciones");
					this.OncantAprobacionesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_meGusta", DbType="Int")]
		public System.Nullable<int> meGusta
		{
			get
			{
				return this._meGusta;
			}
			set
			{
				if ((this._meGusta != value))
				{
					this.OnmeGustaChanging(value);
					this.SendPropertyChanging();
					this._meGusta = value;
					this.SendPropertyChanged("meGusta");
					this.OnmeGustaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantMarcasInadecuado", DbType="Int")]
		public System.Nullable<int> cantMarcasInadecuado
		{
			get
			{
				return this._cantMarcasInadecuado;
			}
			set
			{
				if ((this._cantMarcasInadecuado != value))
				{
					this.OncantMarcasInadecuadoChanging(value);
					this.SendPropertyChanging();
					this._cantMarcasInadecuado = value;
					this.SendPropertyChanged("cantMarcasInadecuado");
					this.OncantMarcasInadecuadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_yoMarqueInadecuado", DbType="Int")]
		public System.Nullable<int> yoMarqueInadecuado
		{
			get
			{
				return this._yoMarqueInadecuado;
			}
			set
			{
				if ((this._yoMarqueInadecuado != value))
				{
					this.OnyoMarqueInadecuadoChanging(value);
					this.SendPropertyChanging();
					this._yoMarqueInadecuado = value;
					this.SendPropertyChanged("yoMarqueInadecuado");
					this.OnyoMarqueInadecuadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deshabilitado", DbType="Int")]
		public System.Nullable<int> deshabilitado
		{
			get
			{
				return this._deshabilitado;
			}
			set
			{
				if ((this._deshabilitado != value))
				{
					this.OndeshabilitadoChanging(value);
					this.SendPropertyChanging();
					this._deshabilitado = value;
					this.SendPropertyChanged("deshabilitado");
					this.OndeshabilitadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Recurso_Aprobacione", Storage="_Aprobaciones", ThisKey="id", OtherKey="idRecurso")]
		public EntitySet<Aprobacione> Aprobaciones
		{
			get
			{
				return this._Aprobaciones;
			}
			set
			{
				this._Aprobaciones.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Recurso_MarcasInadecuado", Storage="_MarcasInadecuados", ThisKey="id", OtherKey="idRecurso")]
		public EntitySet<MarcasInadecuado> MarcasInadecuados
		{
			get
			{
				return this._MarcasInadecuados;
			}
			set
			{
				this._MarcasInadecuados.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Recurso", Storage="_Usuario", ThisKey="id", OtherKey="id", IsForeignKey=true)]
		public Usuario Usuario
		{
			get
			{
				return this._Usuario.Entity;
			}
			set
			{
				Usuario previousValue = this._Usuario.Entity;
				if (((previousValue != value) 
							|| (this._Usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuario.Entity = null;
						previousValue.Recurso = null;
					}
					this._Usuario.Entity = value;
					if ((value != null))
					{
						value.Recurso = this;
						this._id = value.id;
					}
					else
					{
						this._id = default(int);
					}
					this.SendPropertyChanged("Usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Aprobaciones(Aprobacione entity)
		{
			this.SendPropertyChanging();
			entity.Recurso = this;
		}
		
		private void detach_Aprobaciones(Aprobacione entity)
		{
			this.SendPropertyChanging();
			entity.Recurso = null;
		}
		
		private void attach_MarcasInadecuados(MarcasInadecuado entity)
		{
			this.SendPropertyChanging();
			entity.Recurso = this;
		}
		
		private void detach_MarcasInadecuados(MarcasInadecuado entity)
		{
			this.SendPropertyChanging();
			entity.Recurso = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RssFeeds")]
	public partial class RssFeed : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _url;
		
		private int _idMovimiento;
		
		private string _tag;
		
		private string _titulo;
		
		private EntityRef<Movimiento> _Movimiento;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnurlChanging(string value);
    partial void OnurlChanged();
    partial void OnidMovimientoChanging(int value);
    partial void OnidMovimientoChanged();
    partial void OntagChanging(string value);
    partial void OntagChanged();
    partial void OntituloChanging(string value);
    partial void OntituloChanged();
    #endregion
		
		public RssFeed()
		{
			this._Movimiento = default(EntityRef<Movimiento>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_url", DbType="NChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string url
		{
			get
			{
				return this._url;
			}
			set
			{
				if ((this._url != value))
				{
					this.OnurlChanging(value);
					this.SendPropertyChanging();
					this._url = value;
					this.SendPropertyChanged("url");
					this.OnurlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idMovimiento", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idMovimiento
		{
			get
			{
				return this._idMovimiento;
			}
			set
			{
				if ((this._idMovimiento != value))
				{
					if (this._Movimiento.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidMovimientoChanging(value);
					this.SendPropertyChanging();
					this._idMovimiento = value;
					this.SendPropertyChanged("idMovimiento");
					this.OnidMovimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tag", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string tag
		{
			get
			{
				return this._tag;
			}
			set
			{
				if ((this._tag != value))
				{
					this.OntagChanging(value);
					this.SendPropertyChanging();
					this._tag = value;
					this.SendPropertyChanged("tag");
					this.OntagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_titulo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string titulo
		{
			get
			{
				return this._titulo;
			}
			set
			{
				if ((this._titulo != value))
				{
					this.OntituloChanging(value);
					this.SendPropertyChanging();
					this._titulo = value;
					this.SendPropertyChanged("titulo");
					this.OntituloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Movimiento_RssFeed", Storage="_Movimiento", ThisKey="idMovimiento", OtherKey="id", IsForeignKey=true)]
		public Movimiento Movimiento
		{
			get
			{
				return this._Movimiento.Entity;
			}
			set
			{
				Movimiento previousValue = this._Movimiento.Entity;
				if (((previousValue != value) 
							|| (this._Movimiento.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Movimiento.Entity = null;
						previousValue.RssFeeds.Remove(this);
					}
					this._Movimiento.Entity = value;
					if ((value != null))
					{
						value.RssFeeds.Add(this);
						this._idMovimiento = value.id;
					}
					else
					{
						this._idMovimiento = default(int);
					}
					this.SendPropertyChanged("Movimiento");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UsuarioFacebook")]
	public partial class UsuarioFacebook : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idUsuario;
		
		private int _idFacebook;
		
		private int _idMovimiento;
		
		private EntityRef<Usuario> _Usuario;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidUsuarioChanging(int value);
    partial void OnidUsuarioChanged();
    partial void OnidFacebookChanging(int value);
    partial void OnidFacebookChanged();
    partial void OnidMovimientoChanging(int value);
    partial void OnidMovimientoChanged();
    #endregion
		
		public UsuarioFacebook()
		{
			this._Usuario = default(EntityRef<Usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUsuario", DbType="Int NOT NULL")]
		public int idUsuario
		{
			get
			{
				return this._idUsuario;
			}
			set
			{
				if ((this._idUsuario != value))
				{
					if (this._Usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidUsuarioChanging(value);
					this.SendPropertyChanging();
					this._idUsuario = value;
					this.SendPropertyChanged("idUsuario");
					this.OnidUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idFacebook", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idFacebook
		{
			get
			{
				return this._idFacebook;
			}
			set
			{
				if ((this._idFacebook != value))
				{
					this.OnidFacebookChanging(value);
					this.SendPropertyChanging();
					this._idFacebook = value;
					this.SendPropertyChanged("idFacebook");
					this.OnidFacebookChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idMovimiento", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idMovimiento
		{
			get
			{
				return this._idMovimiento;
			}
			set
			{
				if ((this._idMovimiento != value))
				{
					this.OnidMovimientoChanging(value);
					this.SendPropertyChanging();
					this._idMovimiento = value;
					this.SendPropertyChanged("idMovimiento");
					this.OnidMovimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_UsuarioFacebook", Storage="_Usuario", ThisKey="idUsuario", OtherKey="id", IsForeignKey=true)]
		public Usuario Usuario
		{
			get
			{
				return this._Usuario.Entity;
			}
			set
			{
				Usuario previousValue = this._Usuario.Entity;
				if (((previousValue != value) 
							|| (this._Usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuario.Entity = null;
						previousValue.UsuarioFacebooks.Remove(this);
					}
					this._Usuario.Entity = value;
					if ((value != null))
					{
						value.UsuarioFacebooks.Add(this);
						this._idUsuario = value.id;
					}
					else
					{
						this._idUsuario = default(int);
					}
					this.SendPropertyChanged("Usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
