<?xml version="1.0" encoding="utf-8"?><Database Name="IndignadoDB" Class="IndignadoDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost\SQLEXPRESS;Initial Catalog=IndignadoDB;Integrated Security=True" SettingsObjectName="IndignadoServer.Properties.Settings" SettingsPropertyName="IndignadoDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Usuarios" Member="Usuarios">
    <Type Name="Usuario">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idMovimiento" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="apodo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="mail" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="contraseña" Type="System.Data.Linq.Binary" DbType="VarBinary(50) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="latitud" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="longitud" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="fechaRegistro" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="cantRecursosMarcadosInadecuados" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="cantRecursosDeshabilitados" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="banned" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="privilegio" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Association Name="Usuario_Aprobacione" Member="Aprobaciones" ThisKey="id" OtherKey="idUsuario" Type="Aprobacione" />
      <Association Name="Usuario_Asistencia" Member="Asistencias" ThisKey="id" OtherKey="idUsuario" Type="Asistencia" />
      <Association Name="Usuario_Convocatoria" Member="Convocatorias" ThisKey="id" OtherKey="idAutor" Type="Convocatoria" />
      <Association Name="Usuario_Interese" Member="Intereses" ThisKey="id" OtherKey="idUsuario" Type="Interese" />
      <Association Name="Usuario_MarcasInadecuado" Member="MarcasInadecuados" ThisKey="id" OtherKey="idUsuario" Type="MarcasInadecuado" />
      <Association Name="Usuario_Recurso" Member="Recurso" ThisKey="id" OtherKey="id" Type="Recurso" Cardinality="One" />
      <Association Name="Usuario_UsuarioFacebook" Member="UsuarioFacebooks" ThisKey="id" OtherKey="idUsuario" Type="UsuarioFacebook" />
    </Type>
  </Table>
  <Table Name="dbo.Aprobaciones" Member="Aprobaciones">
    <Type Name="Aprobacione">
      <Column Name="idRecurso" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="idUsuario" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Usuario_Aprobacione" Member="Usuario" ThisKey="idUsuario" OtherKey="id" Type="Usuario" IsForeignKey="true" />
      <Association Name="Recurso_Aprobacione" Member="Recurso" ThisKey="idRecurso" OtherKey="id" Type="Recurso" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Asistencias" Member="Asistencias">
    <Type Name="Asistencia">
      <Column Name="idConvocatoria" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="idUsuario" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="hayAsistencia" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Usuario_Asistencia" Member="Usuario" ThisKey="idUsuario" OtherKey="id" Type="Usuario" IsForeignKey="true" />
      <Association Name="Convocatoria_Asistencia" Member="Convocatoria" ThisKey="idConvocatoria" OtherKey="id" Type="Convocatoria" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CategoriasTematicas" Member="CategoriasTematicas">
    <Type Name="CategoriasTematica">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idMovimiento" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="titulo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="miInteres" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="CategoriasTematica_CatTemasConvocatoria" Member="CatTemasConvocatorias" ThisKey="id" OtherKey="idCategoriaTematica" Type="CatTemasConvocatoria" />
      <Association Name="CategoriasTematica_Interese" Member="Intereses" ThisKey="id" OtherKey="idCategoriaTematica" Type="Interese" />
      <Association Name="Movimiento_CategoriasTematica" Member="Movimiento" ThisKey="idMovimiento" OtherKey="id" Type="Movimiento" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CatTemasConvocatorias" Member="CatTemasConvocatorias">
    <Type Name="CatTemasConvocatoria">
      <Column Name="idCategoriaTematica" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="idConvocatoria" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="CategoriasTematica_CatTemasConvocatoria" Member="CategoriasTematica" ThisKey="idCategoriaTematica" OtherKey="id" Type="CategoriasTematica" IsForeignKey="true" />
      <Association Name="Convocatoria_CatTemasConvocatoria" Member="Convocatoria" ThisKey="idConvocatoria" OtherKey="id" Type="Convocatoria" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Convocatorias" Member="Convocatorias">
    <Type Name="Convocatoria">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idMovimiento" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idAutor" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="titulo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="logo" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="latitud" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="longitud" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="fechaInicio" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="fechaFin" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="minQuorum" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="cantAsistencias" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="miAsistencia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Convocatoria_Asistencia" Member="Asistencias" ThisKey="id" OtherKey="idConvocatoria" Type="Asistencia" />
      <Association Name="Convocatoria_CatTemasConvocatoria" Member="CatTemasConvocatorias" ThisKey="id" OtherKey="idConvocatoria" Type="CatTemasConvocatoria" />
      <Association Name="Usuario_Convocatoria" Member="Usuario" ThisKey="idAutor" OtherKey="id" Type="Usuario" IsForeignKey="true" />
      <Association Name="Movimiento_Convocatoria" Member="Movimiento" ThisKey="idMovimiento" OtherKey="id" Type="Movimiento" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Intereses" Member="Intereses">
    <Type Name="Interese">
      <Column Name="idCategoriaTematica" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="idUsuario" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="CategoriasTematica_Interese" Member="CategoriasTematica" ThisKey="idCategoriaTematica" OtherKey="id" Type="CategoriasTematica" IsForeignKey="true" />
      <Association Name="Usuario_Interese" Member="Usuario" ThisKey="idUsuario" OtherKey="id" Type="Usuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Layouts" Member="Layouts">
    <Type Name="Layout">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="layoutFile" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Layout_Movimiento" Member="Movimientos" ThisKey="id" OtherKey="idLayout" Type="Movimiento" />
    </Type>
  </Table>
  <Table Name="dbo.MarcasInadecuados" Member="MarcasInadecuados">
    <Type Name="MarcasInadecuado">
      <Column Name="idRecurso" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="idUsuario" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Usuario_MarcasInadecuado" Member="Usuario" ThisKey="idUsuario" OtherKey="id" Type="Usuario" IsForeignKey="true" />
      <Association Name="Recurso_MarcasInadecuado" Member="Recurso" ThisKey="idRecurso" OtherKey="id" Type="Recurso" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Movimiento" Member="Movimientos">
    <Type Name="Movimiento">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="habilitado" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="logo" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="idLayout" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="latitud" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="longitud" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="maxMarcasInadecuadasRecursoX" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="maxRecursosInadecuadosUsuarioZ" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="maxRecursosPopularesN" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="maxUltimosRecursosM" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Movimiento_CategoriasTematica" Member="CategoriasTematicas" ThisKey="id" OtherKey="idMovimiento" Type="CategoriasTematica" />
      <Association Name="Movimiento_Convocatoria" Member="Convocatorias" ThisKey="id" OtherKey="idMovimiento" Type="Convocatoria" />
      <Association Name="Movimiento_RssFeed" Member="RssFeeds" ThisKey="id" OtherKey="idMovimiento" Type="RssFeed" />
      <Association Name="Layout_Movimiento" Member="Layout" ThisKey="idLayout" OtherKey="id" Type="Layout" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Recursos" Member="Recursos">
    <Type Name="Recurso">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idUsuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="apodoUsuario" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="titulo" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="fecha" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="tipo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="urlLink" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="urlImage" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="urlVideo" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="urlThumb" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="cantAprobaciones" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="meGusta" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="cantMarcasInadecuado" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="yoMarqueInadecuado" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="deshabilitado" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Recurso_Aprobacione" Member="Aprobaciones" ThisKey="id" OtherKey="idRecurso" Type="Aprobacione" />
      <Association Name="Recurso_MarcasInadecuado" Member="MarcasInadecuados" ThisKey="id" OtherKey="idRecurso" Type="MarcasInadecuado" />
      <Association Name="Usuario_Recurso" Member="Usuario" ThisKey="id" OtherKey="id" Type="Usuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.RssFeeds" Member="RssFeeds">
    <Type Name="RssFeed">
      <Column Name="url" Type="System.String" DbType="NChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="idMovimiento" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tag" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="titulo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Movimiento_RssFeed" Member="Movimiento" ThisKey="idMovimiento" OtherKey="id" Type="Movimiento" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UsuarioFacebook" Member="UsuarioFacebooks">
    <Type Name="UsuarioFacebook">
      <Column Name="idUsuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idFacebook" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="idMovimiento" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Usuario_UsuarioFacebook" Member="Usuario" ThisKey="idUsuario" OtherKey="id" Type="Usuario" IsForeignKey="true" />
    </Type>
  </Table>
</Database>