<?xml version="1.0" encoding="utf-8"?><Database Name="IndignadoDB" Class="LinqDataContextDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost\SQLEXPRESS;Initial Catalog=IndignadoDB;Integrated Security=True" SettingsObjectName="IndignadoServer.Properties.Settings" SettingsPropertyName="IndignadoDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Convocatorias" Member="Convocatorias">
    <Type Name="Convocatoria">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="idMovimiento" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idAutor" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="titulo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="geoUbicacion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="inicio" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="fin" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="logo" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="minQuorum" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Movimiento" Member="Movimientos">
    <Type Name="Movimiento">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="latitud" Storage="_geoUbicacion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="logo" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="plantillaEstilo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="maxMarcasInadecuadasRecursoX" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="maxRecursosInadecuadosUsuarioZ" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="maxRecursosPopularesN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="maxUltimosRecursosM" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="habilitado" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="longitud" Type="System.String" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.UsuarioFacebook" Member="UsuarioFacebooks">
    <Type Name="UsuarioFacebook">
      <Column Name="idUsuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idFacebook" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="idMovimiento" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Usuario_UsuarioFacebook" Member="Usuario" ThisKey="idUsuario" OtherKey="id" Type="Usuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Usuarios" Member="Usuarios">
    <Type Name="Usuario">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="idMovimiento" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="apodo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="mail" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="contraseña" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="geoUbicacion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="fechaRegistro" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="banned" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="privilegio" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Usuario_UsuarioFacebook" Member="UsuarioFacebooks" ThisKey="id" OtherKey="idUsuario" Type="UsuarioFacebook" />
    </Type>
  </Table>
</Database>