//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndignadoWeb.MovAdminServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTMovement", Namespace="http://schemas.datacontract.org/2004/07/IndignadoServer.Services")]
    [System.SerializableAttribute()]
    public partial class DTMovement : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idLayoutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float locationLatiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float locationLongField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idLayout {
            get {
                return this.idLayoutField;
            }
            set {
                if ((this.idLayoutField.Equals(value) != true)) {
                    this.idLayoutField = value;
                    this.RaisePropertyChanged("idLayout");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float locationLati {
            get {
                return this.locationLatiField;
            }
            set {
                if ((this.locationLatiField.Equals(value) != true)) {
                    this.locationLatiField = value;
                    this.RaisePropertyChanged("locationLati");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float locationLong {
            get {
                return this.locationLongField;
            }
            set {
                if ((this.locationLongField.Equals(value) != true)) {
                    this.locationLongField = value;
                    this.RaisePropertyChanged("locationLong");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTRssSource", Namespace="http://schemas.datacontract.org/2004/07/IndignadoServer.Services")]
    [System.SerializableAttribute()]
    public partial class DTRssSource : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string urlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tag {
            get {
                return this.tagField;
            }
            set {
                if ((object.ReferenceEquals(this.tagField, value) != true)) {
                    this.tagField = value;
                    this.RaisePropertyChanged("tag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string url {
            get {
                return this.urlField;
            }
            set {
                if ((object.ReferenceEquals(this.urlField, value) != true)) {
                    this.urlField = value;
                    this.RaisePropertyChanged("url");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTRssSourcesCol", Namespace="http://schemas.datacontract.org/2004/07/IndignadoServer.Services")]
    [System.SerializableAttribute()]
    public partial class DTRssSourcesCol : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IndignadoWeb.MovAdminServiceReference.DTRssSource[] itemsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IndignadoWeb.MovAdminServiceReference.DTRssSource[] items {
            get {
                return this.itemsField;
            }
            set {
                if ((object.ReferenceEquals(this.itemsField, value) != true)) {
                    this.itemsField = value;
                    this.RaisePropertyChanged("items");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTThemeCategory", Namespace="http://schemas.datacontract.org/2004/07/IndignadoServer.Services")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(IndignadoWeb.MovAdminServiceReference.DTThemeCategoryMovAdmin))]
    public partial class DTThemeCategory : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idMovementField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int myInterestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string titleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idMovement {
            get {
                return this.idMovementField;
            }
            set {
                if ((this.idMovementField.Equals(value) != true)) {
                    this.idMovementField = value;
                    this.RaisePropertyChanged("idMovement");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int myInterest {
            get {
                return this.myInterestField;
            }
            set {
                if ((this.myInterestField.Equals(value) != true)) {
                    this.myInterestField = value;
                    this.RaisePropertyChanged("myInterest");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string title {
            get {
                return this.titleField;
            }
            set {
                if ((object.ReferenceEquals(this.titleField, value) != true)) {
                    this.titleField = value;
                    this.RaisePropertyChanged("title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTThemeCategoryMovAdmin", Namespace="http://schemas.datacontract.org/2004/07/IndignadoServer.Services")]
    [System.SerializableAttribute()]
    public partial class DTThemeCategoryMovAdmin : IndignadoWeb.MovAdminServiceReference.DTThemeCategory {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTThemeCategoriesColMovAdmin", Namespace="http://schemas.datacontract.org/2004/07/IndignadoServer.Services")]
    [System.SerializableAttribute()]
    public partial class DTThemeCategoriesColMovAdmin : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IndignadoWeb.MovAdminServiceReference.DTThemeCategoryMovAdmin[] itemsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IndignadoWeb.MovAdminServiceReference.DTThemeCategoryMovAdmin[] items {
            get {
                return this.itemsField;
            }
            set {
                if ((object.ReferenceEquals(this.itemsField, value) != true)) {
                    this.itemsField = value;
                    this.RaisePropertyChanged("items");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTUser", Namespace="http://schemas.datacontract.org/2004/07/IndignadoServer.Services")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(IndignadoWeb.MovAdminServiceReference.DTUser_MovAdmin))]
    public partial class DTUser : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool bannedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float locationLatiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float locationLongField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int numberResourcesDisabledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int numberResourcesMarkedInapprField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime registerDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool banned {
            get {
                return this.bannedField;
            }
            set {
                if ((this.bannedField.Equals(value) != true)) {
                    this.bannedField = value;
                    this.RaisePropertyChanged("banned");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fullName {
            get {
                return this.fullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.fullNameField, value) != true)) {
                    this.fullNameField = value;
                    this.RaisePropertyChanged("fullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float locationLati {
            get {
                return this.locationLatiField;
            }
            set {
                if ((this.locationLatiField.Equals(value) != true)) {
                    this.locationLatiField = value;
                    this.RaisePropertyChanged("locationLati");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float locationLong {
            get {
                return this.locationLongField;
            }
            set {
                if ((this.locationLongField.Equals(value) != true)) {
                    this.locationLongField = value;
                    this.RaisePropertyChanged("locationLong");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mail {
            get {
                return this.mailField;
            }
            set {
                if ((object.ReferenceEquals(this.mailField, value) != true)) {
                    this.mailField = value;
                    this.RaisePropertyChanged("mail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int numberResourcesDisabled {
            get {
                return this.numberResourcesDisabledField;
            }
            set {
                if ((this.numberResourcesDisabledField.Equals(value) != true)) {
                    this.numberResourcesDisabledField = value;
                    this.RaisePropertyChanged("numberResourcesDisabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int numberResourcesMarkedInappr {
            get {
                return this.numberResourcesMarkedInapprField;
            }
            set {
                if ((this.numberResourcesMarkedInapprField.Equals(value) != true)) {
                    this.numberResourcesMarkedInapprField = value;
                    this.RaisePropertyChanged("numberResourcesMarkedInappr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime registerDate {
            get {
                return this.registerDateField;
            }
            set {
                if ((this.registerDateField.Equals(value) != true)) {
                    this.registerDateField = value;
                    this.RaisePropertyChanged("registerDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                if ((object.ReferenceEquals(this.usernameField, value) != true)) {
                    this.usernameField = value;
                    this.RaisePropertyChanged("username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTUser_MovAdmin", Namespace="http://schemas.datacontract.org/2004/07/IndignadoServer.Services")]
    [System.SerializableAttribute()]
    public partial class DTUser_MovAdmin : IndignadoWeb.MovAdminServiceReference.DTUser {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTUserDetails_MovAdmin", Namespace="http://schemas.datacontract.org/2004/07/IndignadoServer.Services")]
    [System.SerializableAttribute()]
    public partial class DTUserDetails_MovAdmin : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IndignadoWeb.MovAdminServiceReference.DTResource_MovAdmin[] resourcesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IndignadoWeb.MovAdminServiceReference.DTUser_MovAdmin userField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IndignadoWeb.MovAdminServiceReference.DTResource_MovAdmin[] resources {
            get {
                return this.resourcesField;
            }
            set {
                if ((object.ReferenceEquals(this.resourcesField, value) != true)) {
                    this.resourcesField = value;
                    this.RaisePropertyChanged("resources");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IndignadoWeb.MovAdminServiceReference.DTUser_MovAdmin user {
            get {
                return this.userField;
            }
            set {
                if ((object.ReferenceEquals(this.userField, value) != true)) {
                    this.userField = value;
                    this.RaisePropertyChanged("user");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTResource_MovAdmin", Namespace="http://schemas.datacontract.org/2004/07/IndignadoServer.Services")]
    [System.SerializableAttribute()]
    public partial class DTResource_MovAdmin : IndignadoWeb.MovAdminServiceReference.DTResource {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTResource", Namespace="http://schemas.datacontract.org/2004/07/IndignadoServer.Services")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(IndignadoWeb.MovAdminServiceReference.DTResource_MovAdmin))]
    public partial class DTResource : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int disabledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iLikeItField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int myMarkInapprField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int numberLikesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int numberMarksInapprField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string titleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string urlImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string urlLinkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string urlThumbField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string urlVideoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime date {
            get {
                return this.dateField;
            }
            set {
                if ((this.dateField.Equals(value) != true)) {
                    this.dateField = value;
                    this.RaisePropertyChanged("date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int disabled {
            get {
                return this.disabledField;
            }
            set {
                if ((this.disabledField.Equals(value) != true)) {
                    this.disabledField = value;
                    this.RaisePropertyChanged("disabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iLikeIt {
            get {
                return this.iLikeItField;
            }
            set {
                if ((this.iLikeItField.Equals(value) != true)) {
                    this.iLikeItField = value;
                    this.RaisePropertyChanged("iLikeIt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idUser {
            get {
                return this.idUserField;
            }
            set {
                if ((this.idUserField.Equals(value) != true)) {
                    this.idUserField = value;
                    this.RaisePropertyChanged("idUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int myMarkInappr {
            get {
                return this.myMarkInapprField;
            }
            set {
                if ((this.myMarkInapprField.Equals(value) != true)) {
                    this.myMarkInapprField = value;
                    this.RaisePropertyChanged("myMarkInappr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int numberLikes {
            get {
                return this.numberLikesField;
            }
            set {
                if ((this.numberLikesField.Equals(value) != true)) {
                    this.numberLikesField = value;
                    this.RaisePropertyChanged("numberLikes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int numberMarksInappr {
            get {
                return this.numberMarksInapprField;
            }
            set {
                if ((this.numberMarksInapprField.Equals(value) != true)) {
                    this.numberMarksInapprField = value;
                    this.RaisePropertyChanged("numberMarksInappr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string title {
            get {
                return this.titleField;
            }
            set {
                if ((object.ReferenceEquals(this.titleField, value) != true)) {
                    this.titleField = value;
                    this.RaisePropertyChanged("title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string urlImage {
            get {
                return this.urlImageField;
            }
            set {
                if ((object.ReferenceEquals(this.urlImageField, value) != true)) {
                    this.urlImageField = value;
                    this.RaisePropertyChanged("urlImage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string urlLink {
            get {
                return this.urlLinkField;
            }
            set {
                if ((object.ReferenceEquals(this.urlLinkField, value) != true)) {
                    this.urlLinkField = value;
                    this.RaisePropertyChanged("urlLink");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string urlThumb {
            get {
                return this.urlThumbField;
            }
            set {
                if ((object.ReferenceEquals(this.urlThumbField, value) != true)) {
                    this.urlThumbField = value;
                    this.RaisePropertyChanged("urlThumb");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string urlVideo {
            get {
                return this.urlVideoField;
            }
            set {
                if ((object.ReferenceEquals(this.urlVideoField, value) != true)) {
                    this.urlVideoField = value;
                    this.RaisePropertyChanged("urlVideo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                if ((object.ReferenceEquals(this.usernameField, value) != true)) {
                    this.usernameField = value;
                    this.RaisePropertyChanged("username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTUsersCol_MovAdmin", Namespace="http://schemas.datacontract.org/2004/07/IndignadoServer.Services")]
    [System.SerializableAttribute()]
    public partial class DTUsersCol_MovAdmin : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IndignadoWeb.MovAdminServiceReference.DTUser_MovAdmin[] itemsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IndignadoWeb.MovAdminServiceReference.DTUser_MovAdmin[] items {
            get {
                return this.itemsField;
            }
            set {
                if ((object.ReferenceEquals(this.itemsField, value) != true)) {
                    this.itemsField = value;
                    this.RaisePropertyChanged("items");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTResourcesCol_MovAdmin", Namespace="http://schemas.datacontract.org/2004/07/IndignadoServer.Services")]
    [System.SerializableAttribute()]
    public partial class DTResourcesCol_MovAdmin : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IndignadoWeb.MovAdminServiceReference.DTResource_MovAdmin[] itemsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IndignadoWeb.MovAdminServiceReference.DTResource_MovAdmin[] items {
            get {
                return this.itemsField;
            }
            set {
                if ((object.ReferenceEquals(this.itemsField, value) != true)) {
                    this.itemsField = value;
                    this.RaisePropertyChanged("items");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MovAdminServiceReference.IMovAdminService")]
    public interface IMovAdminService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovAdminService/getMovement", ReplyAction="http://tempuri.org/IMovAdminService/getMovementResponse")]
        IndignadoWeb.MovAdminServiceReference.DTMovement getMovement();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovAdminService/setMovement", ReplyAction="http://tempuri.org/IMovAdminService/setMovementResponse")]
        void setMovement(IndignadoWeb.MovAdminServiceReference.DTMovement dtMovement);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovAdminService/addRssSource", ReplyAction="http://tempuri.org/IMovAdminService/addRssSourceResponse")]
        void addRssSource(IndignadoWeb.MovAdminServiceReference.DTRssSource dtRssSource);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovAdminService/removeRssSource", ReplyAction="http://tempuri.org/IMovAdminService/removeRssSourceResponse")]
        void removeRssSource(IndignadoWeb.MovAdminServiceReference.DTRssSource dtRssSource);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovAdminService/listRssSources", ReplyAction="http://tempuri.org/IMovAdminService/listRssSourcesResponse")]
        IndignadoWeb.MovAdminServiceReference.DTRssSourcesCol listRssSources();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovAdminService/addThemeCategory", ReplyAction="http://tempuri.org/IMovAdminService/addThemeCategoryResponse")]
        void addThemeCategory(IndignadoWeb.MovAdminServiceReference.DTThemeCategoryMovAdmin dtThemeCategory);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovAdminService/removeThemeCategory", ReplyAction="http://tempuri.org/IMovAdminService/removeThemeCategoryResponse")]
        void removeThemeCategory(IndignadoWeb.MovAdminServiceReference.DTThemeCategoryMovAdmin dtThemeCategory);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovAdminService/listThemeCategories", ReplyAction="http://tempuri.org/IMovAdminService/listThemeCategoriesResponse")]
        IndignadoWeb.MovAdminServiceReference.DTThemeCategoriesColMovAdmin listThemeCategories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovAdminService/getUserDetails", ReplyAction="http://tempuri.org/IMovAdminService/getUserDetailsResponse")]
        IndignadoWeb.MovAdminServiceReference.DTUserDetails_MovAdmin getUserDetails(IndignadoWeb.MovAdminServiceReference.DTUser_MovAdmin dtUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovAdminService/getUsersListFull", ReplyAction="http://tempuri.org/IMovAdminService/getUsersListFullResponse")]
        IndignadoWeb.MovAdminServiceReference.DTUsersCol_MovAdmin getUsersListFull();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovAdminService/getUsersListAllowed", ReplyAction="http://tempuri.org/IMovAdminService/getUsersListAllowedResponse")]
        IndignadoWeb.MovAdminServiceReference.DTUsersCol_MovAdmin getUsersListAllowed();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovAdminService/getUsersListBanned", ReplyAction="http://tempuri.org/IMovAdminService/getUsersListBannedResponse")]
        IndignadoWeb.MovAdminServiceReference.DTUsersCol_MovAdmin getUsersListBanned();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovAdminService/banUser", ReplyAction="http://tempuri.org/IMovAdminService/banUserResponse")]
        void banUser(IndignadoWeb.MovAdminServiceReference.DTUser_MovAdmin user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovAdminService/reallowUser", ReplyAction="http://tempuri.org/IMovAdminService/reallowUserResponse")]
        void reallowUser(IndignadoWeb.MovAdminServiceReference.DTUser_MovAdmin user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovAdminService/getResourcesListAll", ReplyAction="http://tempuri.org/IMovAdminService/getResourcesListAllResponse")]
        IndignadoWeb.MovAdminServiceReference.DTResourcesCol_MovAdmin getResourcesListAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovAdminService/getResourcesListEnabled", ReplyAction="http://tempuri.org/IMovAdminService/getResourcesListEnabledResponse")]
        IndignadoWeb.MovAdminServiceReference.DTResourcesCol_MovAdmin getResourcesListEnabled();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovAdminService/getResourcesListDisabled", ReplyAction="http://tempuri.org/IMovAdminService/getResourcesListDisabledResponse")]
        IndignadoWeb.MovAdminServiceReference.DTResourcesCol_MovAdmin getResourcesListDisabled();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovAdminService/enableResource", ReplyAction="http://tempuri.org/IMovAdminService/enableResourceResponse")]
        void enableResource(IndignadoWeb.MovAdminServiceReference.DTResource_MovAdmin resource);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovAdminService/disableResource", ReplyAction="http://tempuri.org/IMovAdminService/disableResourceResponse")]
        void disableResource(IndignadoWeb.MovAdminServiceReference.DTResource_MovAdmin resource);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMovAdminServiceChannel : IndignadoWeb.MovAdminServiceReference.IMovAdminService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MovAdminServiceClient : System.ServiceModel.ClientBase<IndignadoWeb.MovAdminServiceReference.IMovAdminService>, IndignadoWeb.MovAdminServiceReference.IMovAdminService {
        
        public MovAdminServiceClient() {
        }
        
        public MovAdminServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MovAdminServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MovAdminServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MovAdminServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public IndignadoWeb.MovAdminServiceReference.DTMovement getMovement() {
            return base.Channel.getMovement();
        }
        
        public void setMovement(IndignadoWeb.MovAdminServiceReference.DTMovement dtMovement) {
            base.Channel.setMovement(dtMovement);
        }
        
        public void addRssSource(IndignadoWeb.MovAdminServiceReference.DTRssSource dtRssSource) {
            base.Channel.addRssSource(dtRssSource);
        }
        
        public void removeRssSource(IndignadoWeb.MovAdminServiceReference.DTRssSource dtRssSource) {
            base.Channel.removeRssSource(dtRssSource);
        }
        
        public IndignadoWeb.MovAdminServiceReference.DTRssSourcesCol listRssSources() {
            return base.Channel.listRssSources();
        }
        
        public void addThemeCategory(IndignadoWeb.MovAdminServiceReference.DTThemeCategoryMovAdmin dtThemeCategory) {
            base.Channel.addThemeCategory(dtThemeCategory);
        }
        
        public void removeThemeCategory(IndignadoWeb.MovAdminServiceReference.DTThemeCategoryMovAdmin dtThemeCategory) {
            base.Channel.removeThemeCategory(dtThemeCategory);
        }
        
        public IndignadoWeb.MovAdminServiceReference.DTThemeCategoriesColMovAdmin listThemeCategories() {
            return base.Channel.listThemeCategories();
        }
        
        public IndignadoWeb.MovAdminServiceReference.DTUserDetails_MovAdmin getUserDetails(IndignadoWeb.MovAdminServiceReference.DTUser_MovAdmin dtUser) {
            return base.Channel.getUserDetails(dtUser);
        }
        
        public IndignadoWeb.MovAdminServiceReference.DTUsersCol_MovAdmin getUsersListFull() {
            return base.Channel.getUsersListFull();
        }
        
        public IndignadoWeb.MovAdminServiceReference.DTUsersCol_MovAdmin getUsersListAllowed() {
            return base.Channel.getUsersListAllowed();
        }
        
        public IndignadoWeb.MovAdminServiceReference.DTUsersCol_MovAdmin getUsersListBanned() {
            return base.Channel.getUsersListBanned();
        }
        
        public void banUser(IndignadoWeb.MovAdminServiceReference.DTUser_MovAdmin user) {
            base.Channel.banUser(user);
        }
        
        public void reallowUser(IndignadoWeb.MovAdminServiceReference.DTUser_MovAdmin user) {
            base.Channel.reallowUser(user);
        }
        
        public IndignadoWeb.MovAdminServiceReference.DTResourcesCol_MovAdmin getResourcesListAll() {
            return base.Channel.getResourcesListAll();
        }
        
        public IndignadoWeb.MovAdminServiceReference.DTResourcesCol_MovAdmin getResourcesListEnabled() {
            return base.Channel.getResourcesListEnabled();
        }
        
        public IndignadoWeb.MovAdminServiceReference.DTResourcesCol_MovAdmin getResourcesListDisabled() {
            return base.Channel.getResourcesListDisabled();
        }
        
        public void enableResource(IndignadoWeb.MovAdminServiceReference.DTResource_MovAdmin resource) {
            base.Channel.enableResource(resource);
        }
        
        public void disableResource(IndignadoWeb.MovAdminServiceReference.DTResource_MovAdmin resource) {
            base.Channel.disableResource(resource);
        }
    }
}
